### PR TITLE
Fixes overflow issue when block picker is at bottom of screen.

### PR DESCRIPTION
**Pull request by awcodes**
Adds support to Builder Block Picker to determine if it should drop down or up. This prevents overflowing at bottom of screen when open.

Before:
filament-builder-block-overflow

After:
block-picker-drop-up

### CODE REVIEW

**Comment by danharrin** [comment]
I actually want to move to Popper.js for all popups in the entire form package, inc for our Select, MultiSelect and DatePicker components. How would you feel about integrating that instead?

We currently use Alpine to calculate available window space, but that's not a reliable solution and can be replaced.

**Comment by danharrin** [comment]
I understand that this issue is only affecting you for this component, so if you want just integrate Floating UI for the Builder, and then I can handle the rest if you don't feel up to it?

**Comment by awcodes** [comment]
Would you want to implement floating ui as an alpine plugin?

**Comment by danharrin** [comment]
If you can find a nice abstraction, yes!

**Comment by awcodes** [comment]
I’ll see what I can do. Next couple of days are pretty busy at work. Should have some time this weekend. 

Thanks for your feedback.

**Comment by danharrin** [comment]
Thank you!

**Pull request closed without merging**
