### PR TITLE
Fix simple pagination arrows in RTL

### PR DESCRIPTION
**Pull request by asefsoft**
Now arrows are display correctly on both LTR & RTL

was discussed here: https://github.com/laravel-filament/filament/issues/1899

### CODE REVIEW

**Comment by danharrin** [comment]
I'm interested, is there a way to do this in CSS instead of PHP? `rtl:rotate-180`

**Comment by mohamedsabil83** [comment]
> I'm interested, is there a way to do this in CSS instead of PHP? `rtl:rotate-180`

Also, could use `rtl:scale-x-[-1]`

**Comment by asefsoft** [comment]
> I'm interested, is there a way to do this in CSS instead of PHP? `rtl:rotate-180`

Yes that would be better if possible
but I am confusing about this file, why used 3 different components to show pagination icons? => x-tables::icon-button, x-tables::button, x-tables::pagination.item

Interesting thing is that last one has `rtl:rotate-180` on its classes but two others dont have that class.
x-tables::icon-button and x-tables::button are generic components and I dont know how can I add this functionality from outside to them.

p.s: as I noted, x-tables::pagination.item already has `rtl:rotate-180` class on it so current PR commit should be changed and should not push.

**Comment by danharrin** [comment]
AFAIK:

`x-tables::icon-button` - mobile pagination buttons
`x-tables::button` - desktop simple pagination buttons
`x-tables::pagination.item` - desktop standard pagination button

`rtl:rotate-180` should do the trick for all of these

**Comment by danharrin** [comment]
Well, turns out that CSS isn't the easiest option here, as the icon abstractions are locked inside of those Blade components. Thank you @asefsoft

**Comment by asefsoft** [comment]
> Well, turns out that CSS isn't the easiest option here, as the icon abstractions are locked inside of those Blade components. Thank you @asefsoft

As I told you [here](https://github.com/laravel-filament/filament/pull/1935#issuecomment-1073223178) x-tables::pagination.item already has `rtl:rotate:180` so then you **should not** add this changes for that component.
did u consider that?
if did not please dont release otherwise there will be issue on that component for arrows.

**Comment by danharrin** [comment]
I'll fix that in a bit

**Comment by danharrin** [comment]
see, this is why i dont do RTL lol

**Comment by asefsoft** [comment]
so far u did great job on rtl 👍👍

**Comment by mohamedsabil83** [comment]
as I mentioned before, for icons, just `rtl:scale-x-[-1]` did the trick. no need for any rotations.

@danharrin you can revert it and I'll review and fix it.

**Comment by danharrin** [comment]
Sure, I've reverted it now @mohamedsabil83

**Pull request merged**
