### PR TITLE
Add Toggle form field

### PR DESCRIPTION
**Pull request by dllobell**
This pull request adds a new form field, "Toggle", I would prefer calling it "Switch" but it is a reserved word. I think you had this form field in the development roadmap, I did this mainly for practice purposes, it serves more of a starting point but it is a working field.

If you want to make any changes, frontend design, code... you are free to do so or tell me and I will be happy to make them.

image

image

### CODE REVIEW

**Comment by bezhanSalleh** [comment]
i think its a great start and it would be better to add a couple of more methods to cover all the basis:

- label
- onLabel
- offLabel
- onIcon
- offIcon

**Comment by bezhanSalleh** [comment]
@dllobell looks good, but if the on/off label is something other than yes/no/on/off/ok/... then?

Screen Shot 2021-04-20 at 9 11 55 AM

**Comment by danharrin** [comment]
Hi, I think we should keep this simple and not have labels for the time being. In my opinion, the switch should be smaller and inline with the field label, identical to the checkbox.

Here's an example that we can use, which is smaller:
```html
<button type="button" class="relative inline-flex flex-shrink-0 h-6 w-11 border-2 border-transparent rounded-full cursor-pointer transition-colors ease-in-out duration-200 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500 bg-gray-200" x-data="{ on: false }" role="switch" aria-checked="false" :aria-checked="on.toString()" @click="on = !on" x-state:on="Enabled" x-state:off="Not Enabled" :class="{ 'bg-indigo-600': on, 'bg-gray-200': !(on) }">
  <span class="pointer-events-none relative inline-block h-5 w-5 rounded-full bg-white shadow transform ring-0 transition ease-in-out duration-200 translate-x-0" x-state:on="Enabled" x-state:off="Not Enabled" :class="{ 'translate-x-5': on, 'translate-x-0': !(on) }">
    <span class="absolute inset-0 h-full w-full flex items-center justify-center transition-opacity opacity-100 ease-in duration-200" aria-hidden="true" x-state:on="Enabled" x-state:off="Not Enabled" :class="{ 'opacity-0 ease-out duration-100': on, 'opacity-100 ease-in duration-200': !(on) }">
      <svg class="bg-white h-3 w-3 text-gray-400" fill="none" viewBox="0 0 12 12">
        <path d="M4 8l2-2m0 0l2-2M6 6L4 4m2 2l2 2" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path>
      </svg>
    </span>

    <span class="absolute inset-0 h-full w-full flex items-center justify-center transition-opacity opacity-0 ease-out duration-100" aria-hidden="true" x-state:on="Enabled" x-state:off="Not Enabled" :class="{ 'opacity-100 ease-in duration-200': on, 'opacity-0 ease-out duration-100': !(on) }">
      <svg class="bg-white h-3 w-3 text-indigo-600" fill="currentColor" viewBox="0 0 12 12">
        <path d="M3.707 5.293a1 1 0 00-1.414 1.414l1.414-1.414zM5 8l-.707.707a1 1 0 001.414 0L5 8zm4.707-3.293a1 1 0 00-1.414-1.414l1.414 1.414zm-7.414 2l2 2 1.414-1.414-2-2-1.414 1.414zm3.414 2l4-4-1.414-1.414-4 4 1.414 1.414z"></path>
      </svg>
    </span>
  </span>
</button>
```

**Comment by danharrin** [comment]
I've updated this PR, let me know your thoughts:

https://user-images.githubusercontent.com/41773797/115383194-70563e80-a1cd-11eb-8684-5ead5fe43eac.mov

https://user-images.githubusercontent.com/41773797/115383202-73e9c580-a1cd-11eb-8d73-bb1a2ffe5ba9.mov

**Review by ryangjchandler — APPROVED** [review]

**Comment by danharrin** [comment]
Thanks for your work @dllobell!

**Pull request merged**
