### PR TITLE
fix: Markdown editor diff issues

### LINKED ISSUE #2398: Markdown editor doesn't get a red border upon validation errors
### Package

filament/forms

### Package Version

v2.0.0

### Laravel Version

v9.0.0

### Livewire Version

_No response_

### PHP Version

PHP 8.1

### Bug description

The markdown editor does not have a red border when a validation error occurs like inputs or selects.

Upon investigation with @danharrin we noticed `wire:ignore` is the cause of this:

https://github.com/laravel-filament/filament/blob/417e359c7023ed2b9cba319eb3529b16a456b47c/packages/forms/resources/views/components/markdown-editor.blade.php#L17

Removing that line fixes the $error state, but introduces a error within action modals.

### Steps to reproduce

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by danharrin**
Fixes #2398.

### CODE REVIEW

**Comment by themahdavi** [comment]
please bump up these dependencies version 
**@github/file-attachment-element** to v3.1.0
**@github/markdown-toolbar-element** v2.1.1

**Comment by themahdavi** [comment]
And a small bug when click on Image button for attach image:
(I could not find the problem) 

Not Open file attachment windows for select file or image
and write `` and give console error for not find url

**Comment by danharrin** [comment]
> And a small bug when click on Image button for attach image:

This isn't a bug, `` is the syntax for inserting an image. File uploads still work if you drag and drop a file onto the textarea :)

**Comment by themahdavi** [comment]
Ah yes ,
but when add this `` try to load url and give console error 404 .
I think this problem fix on latest version of `@github/file-attachment-element `
Thanks

**Comment by danharrin** [comment]
Closing in favour of #2564.

**Pull request closed without merging**
