### PR TITLE
Update turkish translations

### PR DESCRIPTION
**Pull request by deligoez**
This PR adds the missing Turkish translations and fixes problematic ones.

### CODE REVIEW

**Comment by danharrin** [comment]
Thanks

**Comment by zepfietje** [comment]
@deligoez, just something I noticed: shouldn't the `:label` be `:Label` when used at the start of a translation value to ensure correct capitalization?

**Comment by danharrin** [comment]
oh really, I didn't know that was a feature haha

**Comment by deligoez** [comment]
@zepfietje that would be quite logical, but the problem is auto-capitalization of some Turkish letters is problematic.

In Turkish;
- lowercase of the letter "I" is "ı"
- lowercase of the letter "İ" is "i"

and they are different letters.

Nonetheless I double checked and tried to use `:Label` and see the problem really exists.

So I suggest that we should leave it as it is 😁

**Comment by danharrin** [comment]
Maybe there is a way to rephrase the strings to ensure correct capitalisation?

**Comment by deligoez** [comment]
As far as I know, such a thing is not possible yet If you don't want to dive into Laravel's localization templating 😅

These problems can be deeper than Laravel's localization templating because even `mb_strtolower` has these problems.

https://www.php.net/manual/tr/function.mb-strtolower.php#108346

See the timestamp 😂

**Comment by danharrin** [comment]
I meant that you could rephrase your Turkish maybe to ensure that the `:label` is always in a lowercase position in the string? Sorry I wasn't clear

**Comment by deligoez** [comment]
Oh yes, previous translator/s had tried that in some places. Not a bad idea actually.

In English, right order of the words in a sentence: `Create :label` 
In Turkish, right order of the words in a sentence: `:label Oluştur` 

But; It is possible to write `Oluştur: :label`. That's correct and definitely a solution. But In my opinion, it seems to disrupt the reading flow a bit.

If we come to a conclusion that it is more appropriate to use them this way, I can gladly convert the translations.

**Comment by zepfietje** [comment]
Hmm, I see what you mean. I think it's similar in Dutch, where generally you'd prefer to have the `:Label` first and then the verb.

It's hard for me to judge what's best in Turkish, so I trust you can make a well-founded decision!

**Pull request merged**
