### PR TITLE
Minor RTL enhancements

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by danharrin** [comment]
PERFECT! Thank you @mohamedsabil83

**Comment by danharrin** [comment]
Maybe it's worth PRing Tailwind Forms with that RTL enhancement?

**Comment by mohamedsabil83** [comment]
> PERFECT! Thank you @mohamedsabil83

You're welcome @danharrin 

> Maybe it's worth PRing Tailwind Forms with that RTL enhancement?

Good Idea. I'll do it.

**Comment by danharrin** [comment]
@mohamedsabil83 can you tag this `laravel-filament/filament#961` in the PR so that I know when I can remove the custom CSS? Thanks :)

**Comment by mohamedsabil83** [comment]
I found a PR to solve the same problem since Oct.30 but have not merged yet. I leave a comment there to remember them.

**Comment by danharrin** [comment]
Thank you very much @mohamedsabil83!

**Comment by mohamedsabil83** [comment]
You're welcome @danharrin

**Pull request merged**
