### PR TITLE
Feature/jetstream extension

### PR DESCRIPTION
**Pull request by adam-code-labx**
Hey guys here is a PR package to integrate Filament with Laravel Jetstream.
A lot of developers start from Jetstream and especially use the built in team features.

This package will allow Filament to work directly with a clean install. 
Configuration is overridden to share the same prefix as Jetstream. Currently filament.auth.guard is force back to web.
I will look to extend this to support the custom filament guard by adding the teams trait to the User model if Jetstream exists.

So far this package is specific to Jetstream.
However also in this PR I thought it maybe useful to extend the Navigation system which I have refactored into a new service class. Also added an additional parameter to the config to support overriding the global layout. 
Which essentially means this could be used across multiple administration panel templates, and could even be a good starting point for a separate theming package.

This is by no means complete and I do plan to extend on this idea over the next few days while developing further features for my client. I will be happy to either include the new additions and update this PR or propose some of the below features as idea's towards you next v2 release.

**Planned Features Include**

- Extend table package to support multiple layouts and expandable rows
- Sub resources across multiple tabs which each displaying listing resource
- Jetstream Dashboard implement stats which can be featured directly from each resource
- Additional filters multiple criteria including search by date range 
- Override theme styles published which will be published by this package

At this stage not looking for you guys to merge just to review what has been done so far.
Once completed I will update below.

Thanks everyone! hopefully you find this contribution useful 👍 
Here is a preview of what this looks like so far.

Screenshot 2021-04-16 at 23 53 17

### CODE REVIEW

**Comment by danharrin** [comment]
Hey! Thanks for your contribution here, it looks great.

Jetstream support like this is not something that's on the roadmap at the moment, and we're don't think we have the time or resources to maintain such a package ourselves at the moment. We are happy to merge in any customisation tweaks to the core, if they allow you to maintain this package independently.

Let us know what you think!

**Comment by adam-code-labx** [comment]
Sure sounds good I will divide everything up into separate PR's and perhaps release this one as a partner plugin later.
Jetstream was just an example the idea is to not be restricted to where we can use Filament resources.
 
Will let you know once this is ready which may be a couple of weeks as client work is my priority right now.
@danharrin I will send you a message on Discord with either a loom video or login access once I complete everything :)

**Comment by danharrin** [comment]
> Sure sounds good I will divide everything up into separate PR's and perhaps release this one as a partner plugin later.
> Jetstream was just an example the idea is to not be restricted to where we can use Filament resources.
> 
> Will let you know once this is ready which may be a couple of weeks as client work is my priority right now.
> @danharrin I will send you a message on Discord with either a loom video or login access once I complete everything :)

Thank you! Let me know when you have those PRs up and I'll review them for you 👍

**Comment by danharrin** [comment]
> any update?

As explained, this is not something that will be introduced into core. But, if someone was to create a package to do this I would assist them by modifying Filament to accommodate those customisations.

**Pull request closed without merging**
