### PR TITLE
feat:filament doctor

### PR DESCRIPTION
**Pull request by wychoong**
basic troubleshoot and fix for common inquiry

image

### CODE REVIEW

**Comment by saade** [comment]
idk if we should touch the user published views

**Comment by ryangjchandler** [comment]
@wychoong I'm happy to take this one over if you'd like?

**Comment by wychoong** [comment]
> @wychoong I'm happy to take this one over if you'd like?

sure :)

**Comment by ryangjchandler** [comment]
Will get this ready for a merge today :)

**Comment by ryangjchandler** [comment]
@Saifallak Yeah, that's what I'm waiting for :)

**Comment by pxlrbt** [comment]
Replaced by https://github.com/filamentphp/filament/pull/3176

**Pull request closed without merging**
