### PR TITLE
Update blade-ui-kid/blade-heroicons to 2.x...

### PR DESCRIPTION
**Pull request by telkins**
I'm hoping it's this simple... 🤞 

If more is required, I'd be happy to take a look at whatever needs to be done. 🤓

### CODE REVIEW

**Comment by Saifallak** [comment]
@telkins this would be a breaking change, see https://github.com/filamentphp/filament/issues/3916

**Comment by zepfietje** [comment]
Thanks for commenting @Saifallak.

**Comment by telkins** [comment]
> @telkins this would be a breaking change, see #3916

Thx, @Saifallak .  I was worried about that and even tried to search through previous PRs...but didn't find the one you referenced.  🤓

**Comment by telkins** [comment]
> > @telkins this would be a breaking change, see #3916
> 
> Thx, @Saifallak . I was worried about that and even tried to search through previous PRs...but didn't find the one you referenced. 🤓

Ah...I see...I was only searching closed PRs.  😜

**Pull request closed without merging**
