### PR TITLE
fix: Action attributes not being merged with component attributes

### LINKED ISSUE #2510: withAttributes doesn't work on Actions
### Package

filament/filament

### Package Version

v2.12.11

### Laravel Version

v9.3.0

### Livewire Version

v2.10.4

### PHP Version

8.1.1

### Bug description

`withAttributes()` function doesn't seem to be working correctly on `Pages\Actions`. Whatever attribute I try adding: classes, custom attributes, etc. none seem to be rendered in the final HTML output.

I expected this to render an action button with my custom attributes merged with the predefined ones, just like `$attributes` does in Laravel blade components.

### Steps to reproduce

Overriding this function in an edit page to customize the delete action:

Resources/Resource/Pages/EditPage.php:
```php
//...
protected function getDeleteAction(): Action
    {
        return parent::getDeleteAction()->withAttributes([
            'class' => '!bg-white',
            'someAttribute' => 'someData',
        ]);
    }
//...
```

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by lukas-frey**
fixes #2510

### CODE REVIEW

**Comment by danharrin** [comment]
Technically you should use `extraAttributes()` instead of `withAttributes()`, so I've made it work with both

**Comment by danharrin** [comment]
I've merged it, but since you disallowed maintainers to make edits, I had to branch. Thanks!

**Comment by LukasFreyCZ** [comment]
> I've merged it, but since you disallowed maintainers to make edits, I had to branch. Thanks!

Oh sorry, but that must be some kind of default then, since I haven't changed any settings. 😳Followed the how to contribute guide in the readme. 

Nevertheless, thanks for merging! :-)

**Comment by danharrin** [comment]
Weird, I think there's a little checkbox when you create the PR

**Comment by LukasFreyCZ** [comment]
> Weird, I think there's a little checkbox when you create the PR

Will keep in mind for next time, thanks!

**Pull request merged**
