### PR TITLE
feat: Glassy Auth

### PR DESCRIPTION
**Pull request by awcodes**
Skin login page with Glassy-ness!

Light mode might be a little weird. (at least it is to me, but glass kinda loses its effect the brighter it gets.) lol.

Can still be overridden with custom theme colors.

Screen Shot 2022-05-04 at 3 51 38 PM
Screen Shot 2022-05-04 at 3 51 40 PM
.

### CODE REVIEW

**Comment by danharrin** [comment]
Great! On the dark version, could we make the fade to gray more gradual as its quite harsh at the moment? or, make the primary color darker

**Comment by awcodes** [comment]
Totally. Originally it was three steps from primary to gray 800 to gray 900. But I felt it wasn’t enough of the gray 900. I’ll add the middle step back and update tomorrow.

**Comment by awcodes** [comment]
Added middle stop back to dark mode gradient
Screen Shot 2022-05-05 at 8 42 59 AM
.

**Comment by danharrin** [comment]
Still too harsh IMO, I'll have a play around. Thanks!

**Comment by danharrin** [comment]
How's this?

Screenshot 2022-05-05 at 17 44 43

Screenshot 2022-05-05 at 17 45 08

**Comment by danharrin** [comment]
Screenshot 2022-05-05 at 17 53 38

Screenshot 2022-05-05 at 17 52 42

Screenshot 2022-05-05 at 17 54 54

**Comment by awcodes** [comment]
Looks good to me. 👍

**Comment by awcodes** [comment]
I still don't like the light version, but don't know what else to do with it. LOL. Maybe force the login to be dark mode. IDK.

**Comment by danharrin** [comment]
Yeah I'm not a light fan either, do you think we should get rid of the radial gradient completely on light?

**Comment by danharrin** [comment]
Screw it, let's go with this for now. We can undo it later if there's a negative reaction.

**Pull request merged**
