### PR TITLE
Added content hooks to footer.blade.php

### PR DESCRIPTION
**Pull request by ap1969**
Added footer.start and footer.end content hooks to footer.blade.php

### CODE REVIEW

**Comment by danharrin** [comment]
Can you add the hooks to the docs too please?

**Comment by ap1969** [comment]
Of course. Done!

**Comment by danharrin** [comment]
Cheers

**Comment by pxlrbt** [comment]
Not sure how we want to continue with the naming. Technically this is before and after the footer

**Comment by danharrin** [comment]
Whats the benefit over start and end?

**Comment by ryangjchandler** [comment]
Start and end would be inside of the footer in my mind - before and after would be around the actual elements / rendering.

**Comment by pxlrbt** [comment]
Yep. We already had this discussion, when you wanted to rename some hooks, and make them all `.start`/`.end`

**Comment by pxlrbt** [comment]
Do we want to change this before releasing?

**Comment by danharrin** [comment]
> Yep. We already had this discussion, when you wanted to rename some hooks, and make them all `.start`/`.end`

This is start and end already, so what is there to change?

**Comment by pxlrbt** [comment]
> This is start and end already, so what is there to change?

Yes. We had the discussion to change them all to `.start`/`.end`. But I don't think it makes sense, as there is a difference between `start` and `before`. And in this case `before` would be better suited.

**Comment by danharrin** [comment]
I'll shuffle it around

**Pull request merged**
