### PR TITLE
Bootstraps filament/spatie-laravel-settings-plugin settings creations

### PR DESCRIPTION
**Pull request by bezhanSalleh**
This pull request adds the following abilities to `make:filament-settings-page`:

- Generates a settings class inside `App\Filament\Settings`
- Generates a migration file for the provided settings class
- Updates the plugins documentation to reflect the new changes and provides easy steps for users to follow

### CODE REVIEW

**Comment by danharrin** [comment]
As described on Discord, we should remove some of these features so that the user can (optionally) pass a settings class name from `App\Settings`.

**Comment by bezhanSalleh** [comment]
@danharrin heyo! it now functions exatcly as we talked about.

**Comment by bezhanSalleh** [comment]
@danharrin heyo! it now functions exatcly as we talked about.

**Comment by danharrin** [comment]
Thank you very much!

**Pull request merged**
