### PR TITLE
add filepond-plugin-media-preview

### PR DESCRIPTION
**Pull request by saade**
Adds preview for audios and videos using `nielsboogaard/filepond-plugin-media-preview`

demo

### CODE REVIEW

**Comment by jacksleight** [comment]
The `disablePreview()` option from https://github.com/laravel-filament/filament/pull/1626 could also be extended to cover this, should people want to switch it off:

https://github.com/laravel-filament/filament/blob/51f309b9c23be25a417f5912e40a56a3f2274e3c/packages/forms/resources/js/components/file-upload.js#L84
```js
allowVideoPreview: canPreview,
allowAudioPreview: canPreview,
```

**Comment by danharrin** [comment]
We should merge both PRs to avoid merge conflicts, please organise that amongst yourselves :)

**Comment by danharrin** [comment]
Since #1626 has more impact, lets merge these changes into there if @jacksleight thinks that's a good idea?

**Comment by jacksleight** [comment]
Fine by me if @saade is happy.

**Comment by saade** [comment]
Let's do it!

**Comment by jacksleight** [comment]
Great. I've merged this into my PR, will add the new allow preview options shortly.

**Comment by saade** [comment]
Gonna close this =)

**Pull request closed without merging**
