### PR TITLE
Add missing associate translation file

### PR DESCRIPTION
**Pull request by DanielvdSpoel**
Pretty simple pull request. add a missing translation file

### CODE REVIEW

**Comment by DanielvdSpoel** [comment]
Other dutch speaking people, feel free to correct my grammar. It's not my strongest side.

**Comment by danharrin** [comment]
I'll leave this open for a bit so that the Dutch community can voice their opinions 😅

**Comment by Cannonb4ll** [comment]
We've already had a small discussion about it, @Larsklopstra and I recon "Koppel" & "Koppelen" would be a better alternative as it's more expressive in our language. Daniel is probably going to look into this.

**Comment by DanielvdSpoel** [comment]
Changed it to "Koppel" & "Koppelen"

**Pull request merged**
