### PR TITLE
Improve editor preview when using ViewRecord

### PR DESCRIPTION
**Pull request by mohamedsabil83**

### CODE REVIEW

**Comment by danharrin** [comment]
Can you provide before and after screenshots please?

**Comment by mohamedsabil83** [comment]
**Before**
Screenshot from 2022-04-01 21-54-31


**After**
Screenshot from 2022-04-01 21-54-55

**Comment by mohamedsabil83** [comment]
In fact, it's a ui fix including dark mode

**Comment by danharrin** [comment]
Thanks!

**Comment by mohamedsabil83** [comment]
Welcome!

**Pull request merged**
