### PR TITLE
Update Repeater.php to work with BelongsToMany relationships

### PR DESCRIPTION
**Pull request by yaplej**
Updated RelationshipRepeater to work with BelongsToMany relationships.

### CODE REVIEW

**Comment by danharrin** [comment]
Have you tested this with existing HasManyRepeater components too? You're changing alot of existing functionality.

**Comment by yaplej** [comment]
I have tested the RelationshipRepeater with both HasMany and BelongsToMany relationship and all the basic functionality seems unaffected by the change.  I just tested it with a HasManyRepeater and at least the basics seem to be working just fine.  I probably have a rather simple use case right now so would understand if it needs additional testing.

**Comment by danharrin** [comment]
Apologies for the delay on this, in #2788 I am deprecating HasManyRepeater and allowing users to just use `Repeater::make()->relationship()`. So once that is merged I will look at these changes

**Comment by mustafa-online** [comment]
Can't wait for this to be merged 🎉

**Comment by danharrin** [comment]
Thanks, works fine

**Pull request merged**
