### PR TITLE
fix issue in repeater icons with rtl

### PR DESCRIPTION
**Pull request by maherelgamil**
Before
image

Now 
image

### CODE REVIEW

**Comment by danharrin** [comment]
How about the builder? Also, please ensure that this does not change the LTR styling, it looks like you're removing a border class? Also, keep all RTL classes together at the end of the class list.

**Comment by maherelgamil** [comment]
thanks for this review @danharrin 

- keep all RTL classes together at the end of the class list. [done]

And, borders not removed I fixed it in the last commit.

image

**Comment by danharrin** [comment]
And the builder? :) Have you checked that the border is still there in LTR? You've removed the `border-l` class and added an extra space.

**Comment by maherelgamil** [comment]
@danharrin OMG, i am so sorry for that mistake, i fixed it 

Thanks 🙏

**Comment by danharrin** [comment]
Thanks :)

**Pull request merged**
