### PR TITLE
German translation

### PR DESCRIPTION
**Pull request by pxlrbt**

### CODE REVIEW

**Comment by danharrin** [comment]
Ah, just seen this is "DRAFT". If you need to make any changes, just repush them to the same branch and @ me - I will remerge this.

**Comment by pxlrbt** [comment]
Translations to discuss:

- Attach: "Anhängen" vs "Verknüpfen"
- Create: "Anlegen" vs "Erstellen"
- Create & create another: "Anlegen & weiteren Datensatz anlegen"
- Delete: "Löschen" vs. "Entfernen"

**Comment by pxlrbt** [comment]
> Ah, just seen this is "DRAFT". If you need to make any changes, just repush them to the same branch and @ me - I will remerge this.

It's fully translated, so that's okay. Just wanted to have some feedback from other native speakers.

**Comment by martinmildner** [comment]
> Translations to discuss:
> 
> * Attach: "Anhängen" vs "Verknüpfen"
> * Create: "Anlegen" vs "Erstellen"
> * Create & create another: "Anlegen & weiteren Datensatz anlegen"
> * Delete: "Löschen" vs. "Entfernen"

All in for:
- Attach: "Verknüpfen"
- Create: "Erstellen" oder "Speichern"
- Create & create another: "Erstellen und neu"
- Delete: "Löschen"

**Comment by pxlrbt** [comment]
@danharrin After some feedback here and in Discord I adjusted the translations a little bit.

**Comment by danharrin** [comment]
Cool, I've merged it. Thanks guys.

**Pull request merged**
