### PR TITLE
Add support for descriptions to Text Columns

### PR DESCRIPTION
**Pull request by ralphjsmit**
This PR allows you to add a description above or below the label in a regular text column. I've wanted this on several occasions already and I think it should really be a core feature. It's both very useful and beautiful at the same time. 

```php
TextColumn::make('title')
    ->description(fn(Model $record) => $record->description)
```

By default, the description is shown below the actual label. However, you can choose to display the description above the label using the `->showDescriptionOnTop()` method:

```php
TextColumn::make('title')
    ->description(fn(Model $record) => $record->description)
    ->showDescriptionOnTop()
```

Example below: 

Schermafbeelding 2022-07-30 om 16 08 07

Example on top:

Schermafbeelding 2022-07-30 om 16 06 21

Looks also fine in dark mode:

Schermafbeelding 2022-07-30 om 16 11 37

Thanks!

### CODE REVIEW

**Review by ryangjchandler — CHANGES_REQUESTED** [review]
We should probably allow setting the position from the `description` method too, as a second argument with a default value.

**Comment by ralphjsmit** [comment]
> We should probably allow setting the position from the `description` method too, as a second argument with a default value.

@ryangjchandler Added, thanks!

**Comment by zepfietje** [comment]
What about renaming `description` to `sublabel`?

**Comment by danharrin** [comment]
Not sure `->label()` in Ralph's original example is correct, that is changing the label of the entire column... the main cell content is fetched from the record automatically based on the column name.

**Comment by zepfietje** [comment]
> Not sure `->label()` in Ralph's original example is correct, that is changing the label of the entire column... the main cell content is fetched from the record automatically based on the column name.

Yeah, I think that led me to make the bad `sublabel` suggestion. Only see what's wrong in the example now. 😅

**Comment by sohaibafifi** [comment]
is it relevant to add the HtmlString type too?

**Comment by danharrin** [comment]
Yes, and we should be parsing markdown & sanitising by default as well, probably

**Comment by ralphjsmit** [comment]
> Yes, and we should be parsing markdown & sanitising by default as well, probably

– Added support for `HtmlString`
– Added support for parsing markdown.
– Added HTML sanitization.

**Comment by ralphjsmit** [comment]
Added docs as well.

**Comment by danharrin** [comment]
I think we should switch out `showDescriptionOnTop()` with `descriptionPosition('above' / 'below')`.

`description('Description', string | Closure | null position: 'above')`

`getDescriptionPosition(): ?string`

In the view: `$getDescriptionPosition() ?? 'below'`

**Comment by ralphjsmit** [comment]
Done!

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
