### PR TITLE
Add view action to relation's manager

### PR DESCRIPTION
**Pull request by invaders-xx**
Add a view action to RelationManager. I know that you will not accept to have this action by default, but I didn't know how to implement that as an option with the relation manager. 
Please share your thoughts and I will adapt

### CODE REVIEW

**Comment by danharrin** [comment]
Check how we did the optional "associate" action for RMs, we can do the same thing.

**Comment by invaders-xx** [comment]
I will check and adapt. Thanks for your feedback

**Comment by invaders-xx** [comment]
@danharrin , are you ok ?

**Comment by danharrin** [comment]
Thanks :)

**Pull request merged**
