### PR TITLE
feature: Dynamic builder block labels

### PR DESCRIPTION
**Pull request by danharrin**

### CODE REVIEW

**Comment by invaders-xx** [comment]
@danharrin, How do we activate this functionality ? Thanks for your feedback

**Comment by danharrin** [comment]
```php
Block::make('heading')
    ->label(function ($state) {
        return $state['label'] ?? 'Heading';
    })
    ->schema([
        TextInput::make('label')->lazy()
    ])
```

**Comment by webbipage** [comment]
> ```
> Block::make('heading')
>     ->label(function ($state) {
>         return $state['label'] ?? 'Heading';
>     })
>     ->schema([
>         TextInput::make('label')->lazy()
>     ])
> ```

Hello @danharrin, how can we avoid the ordering number of the blocks appear after the label? For example, I have only one block with the lazy label called "Topic A". The result of the label will be "Topic A 1" now. Thank you!

**Comment by danharrin** [comment]
`Builder::make('content')->withBlockNumbers(false)`

**Pull request merged**
