### PR TITLE
Docs: Fix renderHook names

### PR DESCRIPTION
**Pull request by pxlrbt**

### CODE REVIEW

**Comment by pxlrbt** [comment]
It's already implemented, so it's too late for that. And I think both have their room. Because `body.start` != `body.before`. Maybe

**Comment by Z3d0X** [comment]
You're right!

In the context of `body`(or any other element) it could be meant:
```html
//body.before
<body>
    //body.start
</body>
```

However in the context of `scripts` or `styles`, `before` & `start` means the the same. I guess.

**Comment by danharrin** [comment]
Tbh I feel like the render hooks are incorrectly named, they should be `start` and `end`. But we have to keep BC, so lets add the correct hook above the incorrect one, and not change the docs.

**Comment by danharrin** [comment]
Only added these hooks yesterday (?), and since the docs are our source of truth, I'm just gonna rename them instead of duplicating.

**Pull request merged**
