### PR TITLE
feature: auto-open collapsed groups when sidebar closes

### PR DESCRIPTION
**Pull request by ryangjchandler**
Replaces #1999.

### CODE REVIEW

**Comment by danharrin** [comment]
think you've got a rebase issue 😁

**Comment by ryangjchandler** [comment]
bruh, I just pulled down 2.x

**Comment by danharrin** [comment]
sure it wasn't `main`?

**Comment by ryangjchandler** [comment]
nope, all up to date

**Comment by danharrin** [comment]
ah, its just the assets. weird

**Comment by pxlrbt** [comment]
Doesn't that uncollapse groups on mobile? 😅

**Comment by ryangjchandler** [comment]
@pxlrbt Nope, they're still collapsed on mobile.

**Review by pxlrbt — APPROVED** [review]

**Pull request merged**
