### PR TITLE
Add argument to the disable() method on the form field

### PR DESCRIPTION
**Pull request by edgrosvenor**
Relates to https://github.com/laravel-filament/filament/issues/205

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@edgrosvenor Would you be able to do the same change but from `develop` instead of `main`? There's currently a refactor of fields / forms on there that would make your change invalid. Thanks!

**Comment by edgrosvenor** [comment]
@ryangjchandler Yeah. I'll do that after dinner. Thanks!

**Comment by danharrin** [comment]
Already refactored for `develop` :)

https://github.com/laravel-filament/filament/issues/205#issuecomment-797809572

**Comment by edgrosvenor** [comment]
Thanks, Dan!

**Pull request closed without merging**
