### PR TITLE
Add close button to filter popover

### PR DESCRIPTION
**Pull request by ralphjsmit**
See #1706. I opened a new PR because I rebased my fork, but the old PR still shows 200+ unmerged commits, even though the branches are exactly up-to-date.

 Light:

Schermafbeelding 2022-03-04 om 11 28 13

On hover:

Schermafbeelding 2022-03-04 om 11 28 18

Dark:

Schermafbeelding 2022-03-04 om 11 28 25

Dark on hover:

Schermafbeelding 2022-03-04 om 11 28 29
 

I also added some missing translations.

(PS: that search icon is custom CSS and not Filament.)

### CODE REVIEW

**Comment by danharrin** [comment]
Maybe we should make a "sm" size for the icon-button component and use that? the rounded square looks ok but not consistent with other icon buttons.

**Comment by ralphjsmit** [comment]
Forgive me my dumbness for overlooking the `icon-button` component. Here is the updated variant:

Light:

Schermafbeelding 2022-03-04 om 13 10 39

Light on hover: 

Schermafbeelding 2022-03-04 om 13 10 43

Dark:

Schermafbeelding 2022-03-04 om 13 10 50

Dark on hover:

Schermafbeelding 2022-03-04 om 13 12 11

**Comment by danharrin** [comment]
Thanks!

**Comment by asefsoft** [comment]
It does not display correctly in rtl mode:

image

**Comment by ralphjsmit** [comment]
> It does not display correctly in rtl mode:
> 
> image

How did you set-up RTL mode / what's the best way to reproduce it? Must admit that I've never used RTL in an app.

**Comment by asefsoft** [comment]
> > It does not display correctly in rtl mode:
> > image
> 
> How did you set-up RTL mode / what's the best way to reproduce it? Must admit that I've never used RTL in an app.

In config/app.php set locale to a rtl lang like arabic, farsi etc...

    'locale' => 'fa',

I think it will do it

**Comment by asefsoft** [comment]
> > It does not display correctly in rtl mode:
> > image
> 
> How did you set-up RTL mode / what's the best way to reproduce it? Must admit that I've never used RTL in an app.

It is fixed in new release, no need to do anything:
https://github.com/laravel-filament/filament/pull/1798

**Pull request merged**
