### PR TITLE
Fix collapsible desktop sidebar overlapping with content.

### PR DESCRIPTION
**Pull request by pxlrbt**
This occured when `max_content_width` was set to full. https://github.com/laravel-filament/filament/pull/1885#issuecomment-1073385164

### CODE REVIEW

**Comment by asefsoft** [comment]
> @asefsoft What is the issue - please provide a screenshot.

Two problems:
1. in any setting of `max_content_width `other than `full`, sidebar closes but main area dont get back to the center
2. in RTL direction, very weired situation happens, you should test it

**Comment by pxlrbt** [comment]
@asefsoft Thanks for testing. There was an issue with the class binding that removed the `pl-0` for RTL. Can you try again whether this is fixed for you?

**Comment by danharrin** [comment]
Please resolve the merge conflict, then we can release. Thanks!

**Comment by pxlrbt** [comment]
Done!

**Comment by danharrin** [comment]
Thanks :)

**Pull request merged**
