### PR TITLE
Fix simple pagination arrows in RTL

### PR DESCRIPTION
**Pull request by mohamedsabil83**
This PR replacing #1935 for fixing issue #1899

### CODE REVIEW

**Comment by danharrin** [comment]
Should all buttons have their icons flipped in RTL like that? 🤔

**Comment by asefsoft** [comment]
> Should all buttons have their icons flipped in RTL like that? 🤔

I really don't think so and it is very risky!

**Comment by danharrin** [comment]
Which is why I didn't do `rotate-180` :D

**Comment by mohamedsabil83** [comment]
> Should all buttons have their icons flipped in RTL like that? thinking

With this, it's like a mirror. until now, it useful with all icons I have used

**Comment by danharrin** [comment]
Okay 🤷‍♂️ you're the RTL user so I trust you :)

**Comment by asefsoft** [comment]
image

Which one do u think is ok?
first one has `rtl:scale-x-[-1]`
as i said it is risky and not recommended

**Comment by mohamedsabil83** [comment]
the three components mentioned are for arrows in simple paginations, right?

**Comment by danharrin** [comment]
😬 

you two let me know your final decision, if you need to change anything, submit a new PR

**Comment by mohamedsabil83** [comment]
@danharrin which component renders the trademark shown above?

**Comment by pxlrbt** [comment]
You mean the checkmark? It's the `BooleanColumn`

**Comment by mohamedsabil83** [comment]
Is it use one of these to render icon?
- packages/tables/resources/views/components/button.blade.php
- packages/tables/resources/views/components/icon-button.blade.php
- packages/tables/resources/views/components/pagination/item.blade.php

**Comment by asefsoft** [comment]
it is obvious that we should not mirror all icons just bcoz they are in rtl mode!
two of those components are generic components

**Comment by mohamedsabil83** [comment]
They are mentioned as pagination buttons for that I update them all.
Can you confirm which one is related to the simple pagination specifically?

**Comment by mohamedsabil83** [comment]
> image
> 
> Which one do u think is ok? first one has `rtl:scale-x-[-1]` as i said it is risky and not recommended

@asefsoft can you share the schema to try re-introduced that issue?

**Comment by mohamedsabil83** [comment]
@danharrin can you check if it works as expected? it's ok with me 🤷🏽‍♂️ 
Screenshot from 2022-03-24 15-55-59

**Comment by asefsoft** [comment]
I did it manually to show why we should not mirror every icons. 

if u search filament code, u will see that x-tables::button and x-tables::icon-button are generic and used in many places like actions and filters... and if we flip those icons, then whenever an icon is used in those places it will be flipped and potentially makes situations like that image above

**Comment by asefsoft** [comment]
if u need real example:
image
just add this icon to an action button and see what's happen

```
->prependActions([
            
            Tables\Actions\ButtonAction::make('add_process')->label("ثبت بررسی")
                ->icon('heroicon-o-check')
                ->action('addProcess')
```

**Comment by mohamedsabil83** [comment]
@danharrin I think we can do one of those to fix this conflict:
- new component for pagination button only. or,
- new tag option named e.g. **pagination** or **arrow** similar to **button** tag just apply the class `scale-x-[-1]` which used only for pagination or places that render arrows only

**Comment by asefsoft** [comment]
> we just need to pass a different icon in for RTL, like the original PR. Except we shouldn't do it for the pagination-specific buttons as they aready use CSS.

yes, please 🤷‍♂️🤦‍♂️👍

**Comment by mohamedsabil83** [comment]
Back to the future 😆 
It's up to you @asefsoft, check if only one you changed before or if there is another and send a PR.

**Comment by asefsoft** [comment]
> Back to the future 😆 It's up to you @asefsoft, check if only one you changed before or if there is another and send a PR.

I just want kill myself 😂😂

**Comment by asefsoft** [comment]
> If neither of you want to fix it, I can

you already fixed it, please apply it again. 
thanks

**Comment by mohamedsabil83** [comment]
I'll check and fix it

**Pull request merged**
