### PR TITLE
Badges for navigation items

### PR DESCRIPTION
**Pull request by pxlrbt**
Allow users to set a badge on the navigation items. This could be helpful for showing resources that require an action like a reminder resource.

Usage on resources could look like this:
```php
    public static function getNavigationItems(): array
    {
        [$item] = parent::getNavigationItems();
        $item->badge(Reminder::where('is_open')->count());
        return [$item];
    }
```

This is how it looks. I used the styles from the badge column.

Bildschirmfoto 2022-03-10 um 23 13 58

Bildschirmfoto 2022-03-10 um 23 22 12

### CODE REVIEW

**Comment by danharrin** [comment]
We should define a `getNavigationBadge()` method for resources and pages that makes setting `badge()` easier - like we do for labels, icons and groups.

**Comment by pxlrbt** [comment]
I'm on it.

**Comment by pxlrbt** [comment]
@danharrin Done.

**Comment by danharrin** [comment]
Thank you!

**Comment by asefsoft** [comment]
Thanks but what about logout link on this widget view?
[resources](https://github.com/laravel-filament/filament/tree/2.x/packages/admin/resources)/[views](https://github.com/laravel-filament/filament/tree/2.x/packages/admin/resources/views)/[widgets](https://github.com/laravel-filament/filament/tree/2.x/packages/admin/resources/views/widgets)/account-widget.blade.php

GET route is removed so this logout link throws exception:
The GET method is not supported for this route. Supported methods: POST.

**Pull request merged**
