### PR TITLE
feature: Table content polling

### PR DESCRIPTION
**Pull request by danharrin**

### CODE REVIEW

**Comment by themahdavi** [comment]
Thanks @danharrin 
for more control if we have reload button beside filters icon is good for when user needed to reset table content without full refresh
something like `->reloadable()` on table

**Comment by danharrin** [comment]
I've got no plans for that yet, the table header bar is already crowded with how many buttons we have at the moment

**Comment by themahdavi** [comment]
I don't understand why many buttons crowded tables ?
this features not always needed and some of them not activate together

**Comment by danharrin** [comment]
You can already create a refresh button with `headerActions()`:

```php
Action::make('refresh')
    ->iconButton()
    ->icon('heroicon-o-refresh')
    ->action(function () {})
```

**Pull request merged**
