### PR TITLE
fix resetting tabs and wizard when closing modal

### PR DESCRIPTION
**Pull request by hxnk**
This fixes the issue of wizards and tabs not returning to their original state after a modal closes.

Since resetting them while closing the modal would cause a "flicker" during the transitioning out, the init method on the x-data object is called when reopening the modal instead.

### CODE REVIEW

**Comment by danharrin** [comment]
What are the consequences of watching this property, if it doesnt exist, if you use the wizard or tabs outside of a modal?

**Comment by hxnk** [comment]
Good point!

Added a check to make sure the property is defined.

**Comment by danharrin** [comment]
I'm trying to imagine, maybe it's better to add a modal hook that allows us to reset `mountedTableAction` / `mountedAction` when it is closed. That would mean the modal content is removed from the page and the wizard is reinitialised when the modal is reopened

**Comment by danharrin** [comment]
I've built a different solution, can you please check it still solves your problem @hxnk?

**Comment by hxnk** [comment]
Nice! This solves it too @danharrin :)

**Pull request merged**
