### PR TITLE
Use Filament auth middleware for LW requests.

### PR DESCRIPTION
**Pull request by pxlrbt**
When using a custom auth guard, users are not authenticated during Livewire requests.

I expected issues with the `Login` component, but it's working fine for me. Any other cases, where this global approach could lead to issues?

Reproduction Repo: https://github.com/utsavsomaiya/demo
Create request is not authenticated.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
Would we want to push the entire `auth` stack or just the `Authenticate` middleware?

**Comment by pxlrbt** [comment]
I had this first, but shouldn't it be the same auth middleware for Filament and Livewire requests?

**Comment by wychoong** [comment]
Or should they just update their livewire config?

https://laravel-livewire.com/docs/2.x/authorization
`If you use a different guard to authenticate your users then also add an entry to middleware_group in the livewire config file:`

**Comment by danharrin** [comment]
I also suggested the same thing as Ryan on Discord. @wychoong we cant make them update the LW config, as their frontend LW site might need a different guard to Filament.

**Comment by ajnsn** [comment]
> Just trying to think of unintended side-effects if somebody were to insert their own auth middleware into the config.

fyi: We are using Filament as the "frontend" on the root of the site and have set our own `Authenticate` middleware within Filament's config file. 

Basically because we are using own login redirect route because of a SingleSignOn/Socialite implementation and moreover we are not implementing the `FilamentUser`. 

We are not using a custom guard though.

Without having tested this PR personally, do you guys think this static addition of your `Authenticate` middleware to Livewire will affect us somehow? Thank you!

**Comment by danharrin** [comment]
Nope, this will not affect you. Livewire persistent middleware is only applied to requests IF the middleware was also applied to the original request. So in your case, because Filament's built-in Authenticate was not applied to your request, this won't affect you.

You're probably fine, but if you are struggling to retrieve the `auth()->user()` in Livewire requests, you should also add your Authentication middleware to persistent middleware in a service provider. This has not been changed by this PR at all though.

**Pull request merged**
