### PR TITLE
[Feature] Ability to display icon on widget

### PR DESCRIPTION
**Pull request by mohamedsabil83**
Screenshot from 2022-03-10 14-09-42

### CODE REVIEW

**Comment by ryangjchandler** [comment]
I don't think this visually looks great. I get the reasoning behind it but maybe we're better off with a different design.

**Comment by mohamedsabil83** [comment]
Yep, it's a simple use until we confirm which styles we can add to core of Filament

**Comment by danharrin** [comment]
I think that maybe a small icon on the left of the label might be better.

**Comment by mohamedsabil83** [comment]
ok, I'll change it

**Comment by mohamedsabil83** [comment]
What about this look? if it's ok, I'll push it

Screenshot from 2022-03-10 16-35-15

**Comment by danharrin** [comment]
I think that the icon needs to be a little smaller & there needs to be a little more space between it and the label.

**Comment by danharrin** [comment]
And I don't think we should have `bigIcon()` - you can always create your own Card components if you wish with a custom view.

**Comment by mohamedsabil83** [comment]
Ok, just the small one. I have a plan to multi-style widget but don't know if accept to the core or a separate package but now I'm sure it'll be a separate package 😄 

For the current one, I think it's good now? (w-4 h-4) and (space-x-2) the previous was (w-6 h-6) and (space-x-1)
Screenshot from 2022-03-11 13-37-57

**Comment by danharrin** [comment]
LGTM, thanks!

**Comment by mohamedsabil83** [comment]
You're welcome

**Pull request merged**
