### PR TITLE
fix: Ternary filter indicator

### LINKED ISSUE #3922: TernaryFilter indicators showing as "Yes" or "No" by default and no `->indicator()` changes the displayed text
### Package

filament/tables

### Package Version

v2.15.45

### Laravel Version

v9.28.0

### Livewire Version

v2.10.7

### PHP Version

v8.1.8

### Problem description

Creating a `TernaryFilter` for a table as such:
```php
TernaryFilter::make('email')->label('Has Email')->nullable()
```
or
```php
TernaryFilter::make('email')->label('Has Email')->indicator('Has Email')->nullable()
```
Will result in the "Active filters" indicator to be "Yes" or "No" respectively:
Example of Active filters text

As you could imagine some TernaryFilters can really be as simple as "Yes" or "No" for their values (which is default), and regarding their "Active filter" labels being the same this can be quite confusing:
confusing Active filter indicators

### Expected behavior

As per the documentation I would expect "Has Email: Yes" or "Has Email: No", considering the [documentation](https://filamentphp.com/docs/2.x/tables/filters#active-indicators) and the `->label()`/`->indicator()` I've set.

### Steps to reproduce

Create a simple TernaryFilter without using something to the effect of `->trueLabel('Has Email')->falseLabel('Has No Email')`.

### PR DESCRIPTION
**Pull request by danharrin**
Fixes #3922

### CODE REVIEW

**Comment by titantwentyone** [comment]
Hey @danharrin. Just commenting here as was using a TernaryFilter today and no indicators are being rendered at all. The filter itself works fine but no feedback displayed. Seems to be fine in 2.15.49 before this commit however?

**Comment by danharrin** [comment]
Hey, it should now inherit the behaviour of the SelectFilter, so it should indicate when Yes or No is selected

**Comment by titantwentyone** [comment]
Because of the state of the filter, which could very well be a boolean, it never reaches `return ["{$this->getIndicator()}: {$label}"];`. I think what happens is (thoughts in comments)...

```
        $this->indicateUsing(function (array $state): array {
            if (blank($state['value'] ?? null)) { // if false, will return empty array
                return [];
            }

            $label = $this->getOptions()[$state['value']] ?? null; //no options as its a TernaryFilter so no label

            if (blank($label)) { //...so returns an empty array
                return [];
            }

            return ["{$this->getIndicator()}: {$label}"]; //never reached
        });
```

**Comment by danharrin** [comment]
@titantwentyone #4040 should fix this

**Pull request merged**
