### PR TITLE
Adding further table and page action assertions

### PR DESCRIPTION
**Pull request by titantwentyone**
Includes:

 ```
assertPageActionHasIcon(string $name, string $icon)
assertPageActionDoesNotHaveIcon(string $name, string $icon)
assertPageActionHasLabel(string $name, string $label)
assertPageActionDoesNotHaveLabel(string $name, string $label)
assertPageActionHasColor(string $name, string $color)
assertPageActionDoesNotHaveColor(string $name, string $color)
assertTableActionHasIcon(string $name, string $icon)
assertTableActionDoesNotHaveIcon(string $name, string $icon)
assertTableActionHasLabel(string $name, string $label)
assertTableActionDoesNotHaveLabel(string $name, string $label)
assertTableActionHasColor(string $name, string $color)
assertTableActionDoesNotHaveColor(string $name, string $color)
```

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, could you also do bulk actions? Thanks

**Comment by titantwentyone** [comment]
No worries. Can you merge this PR and I'll create a separate one for bulk actions some time this week?

**Comment by danharrin** [comment]
One thing, should we use `===` for comparisons instead of `==`?

**Comment by titantwentyone** [comment]
If the arguments to the assertions are typed (i.e. `string $icon`), would this make a difference? The return types from `getIcon()`,`getLabel()` and `getColor()` also all return strings (or null). Genuinely unsure!

**Comment by ryangjchandler** [comment]
We should probably use `===` for consistency either way.

**Comment by danharrin** [comment]
Yeah, once it's changed I will merge

**Comment by danharrin** [comment]
Just did it myself :)

**Pull request merged**
