### PR TITLE
fixed markdown-editor list ident

### PR DESCRIPTION
**Pull request by mathijsm0**
Fixed an overlay issue with indents on ordered lists.

before: 
Schermafbeelding 2022-09-19 om 10 50 10

after:
Schermafbeelding 2022-09-19 om 10 49 16

### CODE REVIEW

**Comment by danharrin** [comment]
Hi, I believe that this would reintroduce #3481 for RTL on Chrome?

**Comment by falcomnl** [comment]
This would quite possibly fix #3481. I have no means to confirm this on RTL though.

**Comment by danharrin** [comment]
No, the fix for #3481 was to remove that class - https://github.com/filamentphp/filament/pull/3526/files

You can test RTL by switching your locale to `ar` in `config/app.php`. The bug only exists in Chrome as far as I am aware.

**Comment by falcomnl** [comment]
Ok, fixed it to keep support for RTL in #3481

**Comment by danharrin** [comment]
Thanks :)

**Pull request merged**
