### PR TITLE
Add ability to sort widgets

### PR DESCRIPTION
**Pull request by underdpt**
Hello,

This PR adds the ability to sort widgets, similar how you can sort the right menu options.

It's backwards compatible, so it won't break or change ordering of existing widgets if no order is set.

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, please move the sorting logic to `FilamentManager` so that plugin-registered widgets are also sorted.

Also, add the `$sort` attribute to the base `Widget` class, not the stub.

**Comment by underdpt** [comment]
Hello,

I've just taken a look into this, and I'm not sure which way is preferable, on `FilamentManager`, having in mind that

- `$widgets` is a public property, so it should be ordered by default in case someone is using it directly
- Being `$widgets` a public property, it can be modified by the developer, so the order would be lost

So the two options are:

- Order `$widgets` when calling `registerWidget()`. This would be less performant, and would ignore those two points before
- Order the widgets when calling `getWidgets()`. This is only called one time, so it should be more perfomant. The widgets would be ordered also in case the developer tinkers with `$widgets` property, but not if he uses that property directly.

I think the second one is better, what do you think?

**Comment by danharrin** [comment]
Hi,

Yeah, exactly. I was hinting at using `getWidgets()` to process sorting.

**Comment by underdpt** [comment]
Done.

I'm using a intermediate collection because it will allow for cleaner code when adding #746 to the same method.

**Comment by danharrin** [comment]
Thanks!

**Pull request merged**
