### PR TITLE
docs: add password confirmation modals

### PR DESCRIPTION
**Pull request by jeffgreco13**

### CODE REVIEW

**Comment by SebastiaanKloos** [comment]
@jeffgreco13 I'm creating a tricks feature on the Filament site in a PR. If that gets merged, you could add this trick in there. @danharrin what do you think?

**Comment by danharrin** [comment]
Yeah, I think that unless this actually becomes a feature with a dedicated method for it, it's better as a trick. Thank you though @jeffgreco13

**Comment by jeffgreco13** [comment]
@SebastiaanKloos are you actively working on this Tricks feature right now? I love this idea, and feel I have quite a few to contribute. I'm sure many others would as well.

**Comment by SebastiaanKloos** [comment]
> @SebastiaanKloos are you actively working on this Tricks feature right now? I love this idea, and feel I have quite a few to contribute. I'm sure many others would as well.
> 
> 

Yes I started yesterday. I'm going to  submit a PR this weekend

**Pull request closed without merging**
