### PR TITLE
document command to publish language files

### PR DESCRIPTION
**Pull request by nerdroid23**

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, thanks for these! Could we put these new sections under their own ## heading though please? Thanks!

**Comment by nerdroid23** [comment]
@danharrin sure, no problem. quick question, should i put them under a translations header? or do you have a better idea. i'm open to suggestions.

**Comment by danharrin** [comment]
Pushlishing the translations?

**Comment by nerdroid23** [comment]
@danharrin, i just pushed the requested changes. let me know if there is anything else you'd like me to change

**Comment by danharrin** [comment]
Looks good!

**Comment by danharrin** [comment]
Thanks

**Pull request merged**
