### PR TITLE
Support action groups in notifications

### PR DESCRIPTION
**Pull request by zepfietje**

### CODE REVIEW

**Comment by zepfietje** [comment]
If we can get https://github.com/filamentphp/filament/pull/3443 merged, I can finish this PR as well, @danharrin.

**Comment by zepfietje** [comment]
@danharrin, before merging we need to discuss https://github.com/filamentphp/filament/pull/3443#issuecomment-1232013152.

**Comment by danharrin** [comment]
We can add the Floating to the notifications JS for now until v3

**Comment by danharrin** [comment]
Because this is a new feature, we can just add the Floating UI package installation to the install docs.

**Comment by zepfietje** [comment]
> Because this is a new feature, we can just add the Floating UI package installation to the install docs.

Fair.

**Comment by zepfietje** [comment]
Updated, @danharrin.

**Comment by danharrin** [comment]
Ready to merge?

**Comment by zepfietje** [comment]
> Ready to merge?

Think so. 👀

**Pull request merged**
