### PR TITLE
Docs: Note about referencing other fields from rules() method

### PR DESCRIPTION
**Pull request by intrepidws**

### CODE REVIEW

**Comment by danharrin** [comment]
We actually suggest using `$get` for this which is a consistent API throughout Filament

`required(fn ($get) => filled($get('second_field')))`

**Comment by intrepidws** [comment]
Right but that only works for rules that have a specific method, like `required`. If you need to use the `prohibited_if` rule, which doesn't have it's own method in Filament, then you need to use the `rules()` method, like this:

```php
TextInput::make('state')->rules(['prohibited_if:data.country,US'])
```

Perhaps the answer here is to PR missing rule methods instead?

**Comment by danharrin** [comment]
I think `prohibited()` is one of the very few we are missing

**Comment by intrepidws** [comment]
OK, I added that instead in PR #4376

**Pull request closed without merging**
