### PR TITLE
Prefix session keys

### PR DESCRIPTION
**Pull request by pxlrbt**
Session data may collide with other data otherwise.

### CODE REVIEW

**Comment by danharrin** [comment]
Should we do the same for other session properties within Filament?

**Comment by pxlrbt** [comment]
Yeah I think that would be good. Didn't know any others though 😅

**Comment by danharrin** [comment]
Just search `session` in the codebase ig

**Comment by pxlrbt** [comment]
Found the `per_page` and `toggled_columns` keys. I guess that's it.
They are more specific than `notifications`, but I guess it's good to prefix them all just in case.

Just prefixing will reset the current settings of users. Do you think that's okay? Or should we "migrate" the old to the new value?

**Pull request merged**
