### PR TITLE
New navigation menu button design

### PR DESCRIPTION
**Pull request by tanthammar**
# This PR does two things:

1. Moves the navbar button to a separate blade file.
    1. To accommodate the requests to make this a configurable option.
3. Changes the design of the navbars menu button on @media size 'lg'
    1. Mobile device design remains the same

### Why?
The first time I opened Filament Admin dashboard, I felt that the hamburger icon was misplaced in desktop view. 
It didn’t look related to the expanded sidebar. But of course when clicking it… 

Yes, all developers knows what the "hamburger" menu icon means. But not all users do. 
We need to make self explanatory design wherever possible.

The Mobile device design remains unchanged because the 'hamburger' icon makes perfect sense there.

One may argue that users can get confused by this design change.
In this case you can publish the nav-menu-button.blade.php and keep the "old" design.

### Preview

https://user-images.githubusercontent.com/21239634/188135915-3df72c2b-bb1b-4670-92b4-8c3335c1324b.mov

### Poll response from Discord:

image

# Question
Do I need to `npm run build:styles`?

### CODE REVIEW

**Comment by zepfietje** [comment]
> Do I need to npm run build:styles?

Just running `npm run build` should be fine, @tanthammar.

**Comment by zepfietje** [comment]
For v3 I'd like to make the sidebar fully collapsible on desktop (like on mobile). How would that work with this design change?

**Comment by danharrin** [comment]
Improved the design of the button

Screenshot 2022-09-03 at 14 41 09

Screenshot 2022-09-03 at 14 40 58

**Comment by Cannonb4ll** [comment]
So with this, it's not possible to get the hamburger menu back on the desktop? (Like we used to have)

**Comment by zepfietje** [comment]
> So with this, it's not possible to get the hamburger menu back on the desktop? (Like we used to have)

Yeah... I'm not too happy with forcing this change honestly.

**Comment by Cannonb4ll** [comment]
I suggested in the discord to have this configurable, so you can switch either between the chevron or hamburger, but I guess this wasn't important enough, I'll be having to overwrite the views for future updates now for my customers.

**Comment by zepfietje** [comment]
I definitely think we should revisit this UI change.

**Comment by tanthammar** [comment]
It is configurable, it's moved to a separate component.

**Comment by Cannonb4ll** [comment]
> It is configurable, it's moved to a separate component. 

Care to share how we get the hamburger back on desktop?

**Comment by tanthammar** [comment]
> > It is configurable, it's moved to a separate component.
> 
> Care to share how we get the hamburger back on desktop?

Create a blade file:
`resources/views/vendor/filament/components/layouts/app/topbar/nav-menu-button.blade.php`

```
<button
    x-data="{}"
    x-on:click="$store.sidebar.isOpen ? $store.sidebar.close() : $store.sidebar.open()"
    @class([
        'filament-sidebar-open-button shrink-0 flex items-center justify-center w-10 h-10 text-primary-500 rounded-full hover:bg-gray-500/5 focus:bg-primary-500/10 focus:outline-none',
        'lg:hidden' => ! config('filament.layout.sidebar.is_collapsible_on_desktop'),
        'lg:mr-4 rtl:lg:mr-0 rtl:lg:ml-4' => config('filament.layout.sidebar.is_collapsible_on_desktop'),
    ])>
    <x-heroicon-o-menu class="w-6 h-6"/>
</button>
```

**Comment by tanthammar** [comment]
> For v3 I'd like to make the sidebar fully collapsible on desktop (like on mobile). How would that work with this design change?

@zepfietje  Design is tricky when trying to accommodate for all tastes. Personally I would not want to make it fully collapsible.

A suggestion; 
- keep two nav-menu-button files, like `chevron-nav-menu-button` and `hamburger-nav-menu-button`
- add a config, like `filament.layout.sidebar.hamburger-on-lg` true/false.

In combination with `config('filament.layout.sidebar.width') ` you can make the sidebar fully collapsible and keep the hamburger on lg screens.

It would also remove the need for devs to manually have to override the design change caused by this PR.

We could make `config(filament.layout.sidebar.hamburger-on-lg)` true by default, then no-one notices the design change, but it exists for those who wants it.

Do you want me to wip up a new PR for this?

**Comment by zepfietje** [comment]
Making the sidebar fully collapsible actually doesn't work, as you can't expand it anymore then.

I do understand the design choice of an icon to expand the thin sidebar though. Ideally I'd make it possible to fully hide the sidebar on desktop with a menu icon to toggle it (just like on mobile). Then the current collapsible settings can stay and the arrow icon actually does make sense. However, that would get confusing if you have both the menu and arrow icon (though you wouldn't use both features at the same time.

**Comment by danharrin** [comment]
I don't understand why you'd want the sidebar fully collapsible? I've not discussed that with you before

**Comment by zepfietje** [comment]
> I don't understand why you'd want the sidebar fully collapsible? I've not discussed that with you before

It came to my mind when reviewing this change. Just feels logical to me to have that option. Not an urgent feature for me personally, but was just evaluating this change.

**Comment by danharrin** [comment]
If anyone is going to suggest a good API for making the old design optional, then we can implement it. But I haven't had any satisfactory suggestions yet.

**Comment by tanthammar** [comment]
#3885

**Pull request merged**
