### PR TITLE
Add ability to disable RelationManager list edit action

### PR DESCRIPTION
**Pull request by mallardduck**
This just adds a very simple method to complement the `canCreate`, `canDelete`, and `canDetach` methods. The benefit of this is a very easy way to make the relation manager only allow attach and detach actions.

### CODE REVIEW

**Comment by monoman81** [comment]
I made the same question earlier today on the filament discord server. What i have to do is this:

```
use Filament\Resources\RelationManager\ListRecords;
class ListMediaRecords extends ListRecords
{
    public function getRecordActions()
    {
        return [
        ];
    }
}
```
And in the RelationManager class override the $components static variable to tell filament that use my custom ListMediaRecords:

```
protected static $components = [
        'attach' => RelationManager\AttachRecord::class,
        'create' => CreateMediaRecord::class,
        'edit' => RelationManager\EditRecord::class,
        'list' => ListMediaRecords::class,
];
```
It works but seems to me a little bit of overkill if only need to remove the Edit action.

**Comment by mallardduck** [comment]
@monoman81 - Thanks for providing that input, I think this helps to show how this PR could be a simpler alternative to that method. This method will also make the control of edit abilities match the others as mentioned in my OP.

**Comment by monoman81** [comment]
I agree with you. Regards.

**Comment by danharrin** [comment]
Thank you!

**Pull request merged**
