### PR TITLE
feat: Select component can allow HTML in the choices.js config

### PR DESCRIPTION
**Pull request by consignr**
This PR adds a method to the select component to enable the allowHtml option in the choices.js config. The developer can then render html for the select options which is useful for users with avatars, countries with flags...etc

image

``` 
            Select::make('user_id')
                    ->label('User')
                    ->allowHtml()
                    ->searchable() 
                    ->getSearchResultsUsing(function (string $search) {
                        $users = User::where('name', 'like', "%{$search}%")->limit(50)->get();
                        return $users->mapWithKeys(function ($user) {
                            return [
                                $user->getKey() => 
                                    view('filament.components.select-user-result')
                                        ->with('name', $user->name)
                                        ->with('email', $user->email)
                                        ->with('image', $user->image)
                                        ->render()
                                    ];
                        })->toArray();
                    }) 
                    ->getOptionLabelUsing(function ($value): string {
                        $user = User::find($value);
                        return view('filament.components.select-user-result')
                            ->with('name', $user->name)
                            ->with('email', $user->email)
                            ->with('image', $user->image)
                            ->render();
                    }) ```

### CODE REVIEW

**Comment by danharrin** [comment]
Thanks, but...

Be safe! Sanitise your options HTML! This will introduce XSS attacks :)

**Comment by danharrin** [comment]
Please submit a code example (for example the user avatar & email) to `https://filamentphp.com/tricks`, many people will find it useful :)

**Comment by consignr** [comment]
Thank for merging! I've submitted a trick (with sanitised HTML). I couldn't upload my screenshots though.

**Comment by danharrin** [comment]
Did you try dragging and dropping your image onto the textarea?

**Comment by consignr** [comment]
Sorted. Thanks! 👍

**Comment by blite** [comment]
great work!, example works for me 

I wonder if example should use profile_photo_url from jetpack, but I don't know how many people continue using that.  

I am digging in now for my actual use case.

**Pull request merged**
