### PR TITLE
feature: Refactor select inputs to use Choices.js, add action support to form components, including `BelongsToSelect` create action / modal

### LINKED ISSUE #1836: Issue occurred when hit CreateAnother after editing
### Package

filament/filament

### Package Version

v2.10.23

### Laravel Version

v9.3.1

### Livewire Version

v2.10.4

### PHP Version

PHP 8.1.3

### Bug description

After editing an existing record and starting to create a new one, when hit **Create** saved without issue. but, if hit **Create and Create another**, saved but show the following issue and the saved record appears after refreshing the page.

Screenshot from 2022-03-08 23-31-40
Screenshot from 2022-03-08 23-43-19

### Steps to reproduce

Create a table with two columns:
- name => string
- is_enabled => boolean

This is the form schema:
```php
public static function form(Form $form): Form
{
    return $form
        ->schema([
            Forms\Components\TextInput::make('name')
                ->label(__('Name'))
                ->disableAutocomplete()
                ->required()
                ->unique(ignorable: fn (?Model $record): ?Model => $record),
            Forms\Components\Toggle::make('is_enabled')
                ->label(__('Enabled / Disabled'))
                ->default(true)
                ->inline(false)
                ->hint(fn ($state) => $state ? '<span class="font-bold text-success-700">'.__('Enabled').'</span>' : '<span class="font-bold text-primary-700">'.__('Disabled').'</span>')
                ->reactive(),
        ])
    ;
}
```

### Relevant log output

_No response_

### LINKED ISSUE #1966: Default options are not selected in MultiSelect dropdown
### Package

filament/filament

### Package Version

v2.10.33

### Laravel Version

v9.5.1

### Livewire Version

v2.10.4

### PHP Version

PHP 8.1.2

### Bug description

Default options in a MultiSelect field are not selected in the dropdown.

### Steps to reproduce

The field:
```php
MultiSelect::make('testing')
    ->default([2])
    ->options([
        1 => 'Option 1',
        2 => 'Option 2',
        3 => 'Option 3',
    ]),
```

Before clicking dropdown (looks fine):
billede

When clicking dropdown (Bug: Option 2 is not checked):
billede

I would expect the dropdown to look like this (Expected: Option 2 to be checked):
billede

Instead you're now able to double select the same option:
billede

### Relevant log output

_No response_

### LINKED ISSUE #2065: Dependant Multiselect - duplicate options and not reactive
### Discussed in https://github.com/laravel-filament/filament/discussions/2035

<div type='discussions-op-text'>

<sup>Originally posted by **johncarter-** March 28, 2022</sup>
I'm trying to dynamically load a different set of options on a `Multiselect` based on the choice from a `Select`.

Two problems I'm facing:

1. I'm getting duplicate options in the `Multiselect` options
2. The `Multiselect` doesn't refresh on change of the select

See short video: https://vimeo.com/693103553/5985b15db3

Here's my code:

```php
Repeater::make('products_from')
    ->columns(2)
    ->schema([
        Select::make('product_attribute')
            ->reactive()
            ->options([
                'brand' => 'Brand',
                'type' => 'Type'
            ]),
        MultiSelect::make('selected_attributes')
            //->getSearchResultsUsing(fn (Closure $get, string $query) => Technology::where('name', 'like', "%{$query}%")->limit(50)->pluck('name', 'id'))
            ->options(function (Closure $get) {
                ray($get('product_attribute'));

                if (!$get('product_attribute')) {
                    return [];
                }

                $attributeModel = match ($get('product_attribute')) {
                    'brand' => ProductBrand::class,
                    'type' => ProductType::class
                };

                return $attributeModel::all()->pluck('name', 'id')->toArray();
            }),
    ])
```

Anyone know what I'm doing wrong?</div>

### LINKED ISSUE #2222: Searchable select doesn't show default value
### Package

filament/forms

### Package Version

v2.11.3

### Laravel Version

v8.83.9

### Livewire Version

v2.10.5

### PHP Version

8.1.4

### Bug description

When using a select component with a default value, it shows that default value selected when loading the page. But if I add `searchable` then the default value is not selected by default

### Steps to reproduce

```php
Components\Select::make('cliente.id')
    ->label('Selecciona un cliente')
    ->searchable()
    // phpcs:ignore ImportDetection.Imports.RequireImports.Symbol
    ->options(fn () => \auth()->user()?->empresa?->clientes()->pluck('nombre', 'id') ?? [])
    ->reactive()
    ->afterStateUpdated(
        fn () => $this->emitTo(NuevaMatricula::class, 'clienteCambiado', $this->cliente->id)
    )
    ->disabled(! empty($this->matriculaId))
    ->default($this->clienteId)
    ->required(),
```

### Relevant log output

_No response_

### LINKED ISSUE #2250: Searchable select doesn't reevaluate closure options
### Package

filament/forms

### Package Version

v2.11.0

### Laravel Version

9.9

### Livewire Version

v2.10.5

### PHP Version

8.1.4

### Bug description

Using a `BelongsToSelect` with a `options` callable, I set the available options for the select using a dependent sibiling's value by calling `$get('the_dependent_field')`. 

When changing the dependents value, a non searchable select correctly updates with the values. However, if the select is marked as searchable, the options callable is called on the backend (confirmed by logging) but the select `listboxOptionsList` contains the original values from the dependent.

### Steps to reproduce

without searchable
```php
protected function getManageTicketFormSchema(): array
    {
        return [
Forms\Components\BelongsToSelect::make('ticket_board_id')
                        ->relationship('ticketBoard', 'name')
                        ->options(fn() => TicketBoard::all()->pluck('name', 'id'))
                        ->searchable()
                        ->label('Ticket Board')
                        ->reactive(),
Forms\Components\BelongsToSelect::make('ticket_status_id')
                        ->relationship('ticketStatus', 'name')
                        ->options(fn($get) => TicketBoard::whereId($get('ticket_board_id'))->firstOrFail()->allAllowedStatuses->pluck('name', 'id'))
                        ->default(fn($get) => TicketBoard::whereId($get('ticket_board_id'))->firstOrFail()->new_ticket_status_id)
                        ->label('Status')
                        ->placeholder("Select One")
                        ->disablePlaceholderSelection()
//                        ->searchable()
    ]
}
```
### initial state
Screen Shot 2022-04-28 at 11 14 28 AM
ne")
### changed dependent
Screen Shot 2022-04-28 at 11 14 35 AM

with searchable
```php
protected function getManageTicketFormSchema(): array
    {
        return [
Forms\Components\BelongsToSelect::make('ticket_board_id')
                        ->relationship('ticketBoard', 'name')
                        ->options(fn() => TicketBoard::all()->pluck('name', 'id'))
                        ->searchable()
                        ->label('Ticket Board')
                        ->reactive(),
Forms\Components\BelongsToSelect::make('ticket_status_id')
                        ->relationship('ticketStatus', 'name')
                        ->options(fn($get) => TicketBoard::whereId($get('ticket_board_id'))->firstOrFail()->allAllowedStatuses->pluck('name', 'id'))
                        ->default(fn($get) => TicketBoard::whereId($get('ticket_board_id'))->firstOrFail()->new_ticket_status_id)
                        ->label('Status')
                        ->placeholder("Select One")
                        ->disablePlaceholderSelection()
                        ->searchable()
    ]
}
```
Screen Shot 2022-04-28 at 11 17 26 AM
Screen Shot 2022-04-28 at 11 17 39 AM

### Relevant log output

```shell
--- original options populated when the form was filled ---
[2022-04-28 14:46:13] local.INFO: populating ticket status {"board":18276486811313,"result":{"Illuminate\\Support\\Collection":{"18276486707790":"New","18276486941448":"Updated","18276486966929":"Waiting","18276486746643":"Closed"}}} 

--- after changing the dependent select ---
[2022-04-28 14:46:21] local.INFO: populating ticket status {"board":"18494810344534","result":{"Illuminate\\Support\\Collection":{"18276486707790":"New","18276486746643":"Closed"}}}
```

### PR DESCRIPTION
**Pull request by ryangjchandler**

### CODE REVIEW

**Comment by robertdrakedennis** [comment]
Don't mean to unnecessarily bump this, but what's the status on this? Does this need any help or work?

**Comment by danharrin** [comment]
Yeah we're still working on it. We're also integrating a new select library at the same time so it'll take a little while longer.

**Comment by danharrin** [comment]
Todo: reflect #2221

**Comment by danharrin** [comment]
Todo: make closures static

**Comment by ryangjchandler** [comment]
@danharrin Have made some of the `Closure`s static - will need a rebase on `2.x` to see if there's any others as well.

**Comment by danharrin** [comment]
This seems to be working now! :D

**Comment by danharrin** [comment]
- [ ] Dark mode
- [ ] Get tom-select to to work in action modals
- [ ] Debug performance issues

**Comment by ryangjchandler** [comment]
@danharrin Since we're moving some action stuff into the support package, can we also add a new `invisible()` method to the base `Action` class or make the default view for an action the invisible view?

**Pull request merged**
