### PR TITLE
Allow HTML for notification messages

### PR DESCRIPTION
**Pull request by pxlrbt**
This would allow us to put links or a bit of formatting inside the message. For example, a link to a downloaded file.

### CODE REVIEW

**Comment by ryangjchandler** [comment]
If we do this, we should probably change the surrounding `<p>` tag to a `<div>`, so it's a little more semantic. Thoughts?

**Comment by pxlrbt** [comment]
You are right. Totally missed that.

**Comment by danharrin** [comment]
Is there any chance of an XSS from allowing HTML like this?

**Comment by pxlrbt** [comment]
> Is there any chance of an XSS from allowing HTML like this?

Since the HTML comes from Filament or plugins I don't see much risk here. Only if stuff gets injectected into the session data, but I guess you have other issues then 😅

**Comment by danharrin** [comment]
I'm thinking, if people put the name of the record in the notification from user input, then it could be vulnerable.

If we allow markdown instead with `Str::markdown()`, does that strip dangerous HTML for us?

**Comment by ralphjsmit** [comment]
> If we allow markdown instead with `Str::markdown()`, does that strip dangerous HTML for us?

Yes, I just tested that earlier this week, whether it's save to `{!! Str::markdown($userInput) !!}`. The result was that things like `<iframes>` were stripped, but normal Markdown was rendered correctly.

**Comment by danharrin** [comment]
Great, lets do that @pxlrbt @ryangjchandler ?

**Comment by pxlrbt** [comment]
I wrapped the notification messages inside `Str::markdown()`. As a side effect the message is wrapped in <p>-Tags but I don't think that's an issue as we don't have any general styling.

**Pull request merged**
