### PR TITLE
Add a disabled style to text, textarea fields

### PR DESCRIPTION
**Pull request by jeffgreco13**
Update text-field and textarea components to include disabled: state styling. Requires update to tailwind.config.js

### CODE REVIEW

**Comment by danharrin** [comment]
Hey, thanks for your work here.

By default in JIT mode, all variants are enabled, so [no changes to `tailwind.config.js` are required](https://tailwindcss.com/docs/just-in-time-mode#all-variants-are-enabled).

Also, why is disabled state only active for invalid fields? I think the class belongs in the first class line.

**Comment by danharrin** [comment]
I'm going to hold off on merging this and implement it consistently across all fields. Thanks for your work.

**Comment by jeffgreco13** [comment]
Sorry @danharrin I let this solution slide due to some client commitments. Will be better next time!

**Comment by danharrin** [comment]
No worries!

**Pull request closed without merging**
