### PR TITLE
value should be casted to string

### PR DESCRIPTION
**Pull request by Gummibeer**
Right now the exact model value is used - with a package like https://github.com/spatie/laravel-enum this leads to problems.
This casts the real model value to string - this still works with numeric array keys as PHP casts the string back to integer if needed.

### CODE REVIEW

**Comment by danharrin** [comment]
What setup is causing you problems?

**Comment by Gummibeer** [comment]
The problem occurs on edit view if I have a model with enum attribute cast.
So `$post->status` is an instance of `StatusEnum`. The corresponding select has all enum values as options. But as objects can't be array keys it uses the string value.

Now if I open the edit view of that model I get an exception.

I can provide real code if wanted. But am on phone right now, so first tried to describe.

**Comment by danharrin** [comment]
Do you think it'd be better to cast it with `(string)` instead of using `strval()`?

**Comment by Gummibeer** [comment]
I think that the result is the same. So I don't care. Could also be casted with `string` argument typehint (I think).
I don't have performance benchmarks but this function isn't called a million times so it's unimportant.

Whatever feels better for you!? 😉

**Comment by danharrin** [comment]
Yeah, if you could switch to using `(string) $value` that would be awesome. Thanks!

**Comment by ryangjchandler** [comment]
@Gummibeer You okay making the change @danharrin asked for? If not, I can do it for you so we can get this merged in.

**Comment by danharrin** [comment]
All done, thanks :)

**Comment by Gummibeer** [comment]
Sorry, have planned to do it this evening.^^

**Pull request merged**
