### PR TITLE
Tweak file upload layout, add filepond-plugin-media-preview, add disable preview option

### PR DESCRIPTION
**Pull request by jacksleight**
This PR makes some minor tweaks to the compact file upload layout, so that it fits nicely with the other fields and is actually a bit more compact. Changes are:

* The `min-height` on the drop area element has been tweaked so it that it's the same height as the uploading/file element, removing the dead space below the field when a value is set
* The padding on the uploading/file element has been tweaked so it renders at exactly 42px high, the same height as Filament single line fields
* The drop area label text size has been reduced slightly, so it will fit at smaller widths
* The dark mode background on the drop area element has been removed, as it covers the border and the root element already has the right background colour

This PR also adds a `disablePreview()` method, to switch off the image preview feature.

These changes allow for a very compact and consistently sized single file upload field that fits alongside other fields.

Before:

Screenshot 2022-02-15 at 15 47 57

After:

Screenshot 2022-02-15 at 15 49 37

Blank values:

Screenshot 2022-02-16 at 09 46 48

Also includes filepond-plugin-media-preview feature from https://github.com/laravel-filament/filament/pull/1643

### CODE REVIEW

**Comment by danharrin** [comment]
I think I actually prefer `compact` as a default. What does it look like with the image preview?

**Comment by jacksleight** [comment]
Yeah me too. With preview:

Screenshot 2022-02-16 at 12 23 19

And multiple files (without preview):

Screenshot 2022-02-16 at 12 23 58

Let me know if you'd like me to change it to use this stying by default instead of just compact.

**Comment by danharrin** [comment]
Yeah, multi file spacing is a must. Then, we can use a compact layout by default :)

Make sure that the `->avatar()` layout isnt broken by any of this, btw.

**Comment by jacksleight** [comment]
Added some spacing:

Screenshot 2022-02-16 at 12 54 22

At the moment these changes have no impact on the `avatar()` layout, as that uses `compact circle` and the styles target `compact` only.

Screenshot 2022-02-16 at 13 02 58

The only thing I've (just) done is set the initial `min-height` correctly on an avatar upload, so that doesn't cause a height change when FilePond loads.

**Comment by jacksleight** [comment]
@danharrin @saade 

One hiccup. Despite the `allowVideoPreview` and `allowAudioPreview` options existing in filepond-plugin-media-preview:

https://github.com/nielsboogaard/filepond-plugin-media-preview/blob/db25fa6ea9424a1d4679f311dbd0904f1228ed95/src/js/index.js#L59

It doesn't look like they're actually implemented.

Not sure if there's another way we can disable the plugin or if we'd need to wait for filepond-plugin-media-preview to fix it?

**Comment by saade** [comment]
> @danharrin @saade
> 
> One hiccup. Despite the `allowVideoPreview` and `allowAudioPreview` options existing in filepond-plugin-media-preview:
> 
> https://github.com/nielsboogaard/filepond-plugin-media-preview/blob/db25fa6ea9424a1d4679f311dbd0904f1228ed95/src/js/index.js#L59
> 
> It doesn't look like they're actually implemented (as far as I can see).
> 
> Not sure if there's another way we can disable the plugin or if we'd need to wait for filepond-plugin-media-preview to fix it?

idk if @nielsboogaard will ever implement this. although the repo had an update 5 days ago, npm does not received a new version since June 2021. Me and @danharrin talked about forking this and maintain it ourselves. If thats ok, i can fork and make the chages, or feel free if you want to

**Comment by jacksleight** [comment]
Yeah it doesn't look like it's that frequently updated. If you can fork it and implement those options that'd be great!

**Comment by nielsboogaard** [comment]
Hey guys, thanks for the PR. Will have a look at it today or tomorrow. I don't regularly work on this plugin indeed, but are open for pull requests of course!

**Comment by saade** [comment]
also, @nielsboogaard all of your filepond plugins seems to fit very nice with filament, we also need the security patches at leat :)

**Comment by saade** [comment]
> Clear. Will have a look this afternoon at the mentioned configuration options. Will also create a release soonish containing the security fixes.

Thank you!

**Comment by nielsboogaard** [comment]
Configuration options are taken into account now, and all dependencies are bumped to latest version. See https://github.com/nielsboogaard/filepond-plugin-media-preview, if you use latest version 1.0.11 you should be good to go.

**Comment by jacksleight** [comment]
Brilliant. Can confirm Filament's `disablePreview()` option is now working with video and audio files.

Thanks Niels!

**Comment by jacksleight** [comment]
Should I set the default FileUpload layout to compact now? I think that's the last thing outstanding...

**Comment by saade** [comment]
I think so

**Comment by saade** [comment]
@danharrin can we get this merged? Really needing this 😛

**Comment by danharrin** [comment]
Perfect! Thank you so much.

**Comment by robertorinaldi-dev** [comment]
> Added some spacing:
> 
> Screenshot 2022-02-16 at 12 54 22
> 
> At the moment these changes have no impact on the `avatar()` layout, as that uses `compact circle` and the styles target `compact` only.
> 
> Screenshot 2022-02-16 at 13 02 58
> 
> The only thing I've (just) done is set the initial `min-height` correctly on an avatar upload, so that doesn't cause a height change when FilePond loads.

The spacing seems to work only with 2 files, not more

**Comment by jacksleight** [comment]
@robertorinaldi-dev Thanks, have submitted a fix.

**Pull request merged**
