### PR TITLE
Allow custom classes in icon column

### PR DESCRIPTION
**Pull request by wit3**

### CODE REVIEW

**Comment by danharrin** [comment]
Hm not sure about this. Would need to do the same everywhere else (for consistency) and I think we probably have cases where it would be a breaking change..

**Comment by danharrin** [comment]
Decided this will be fine for the icon column. Thank you :)

**Comment by Wit3** [comment]
Thanks

**Comment by Wit3** [comment]
If i create a PR for BadgeColumn, same implementation, what do you think about?

**Comment by danharrin** [comment]
Hmm, sure 👍

**Pull request merged**
