### PR TITLE
add georgian(ka) language translations

### PR DESCRIPTION
**Pull request by liorocks**

### CODE REVIEW

**Comment by danharrin** [comment]
Hey! Thanks for these. There are others in /packages/forms/resources/lang and /packages/tables/resources/lang, mind checking those out too?

**Comment by Landish** [comment]
Sure, i'll update them as soon as i can.

**Comment by Landish** [comment]
@danharrin I've updated. Can you check it out?

**Comment by danharrin** [comment]
Thanks!

**Pull request merged**
