### PR TITLE
Fix hour, minute, seconds in date-time-picker

### PR DESCRIPTION
**Pull request by tanthammar**
If you increment or decrement hour, minute, seconds in the date-time-picker and exceed the allowed range, the value falls back to current dayjs().

Example if the hour is 14, incrementing to 24 resets the value to 14 instead of 0.
The same goes for minutes, seconds, if current is, let's say 45 and you increment to 60 it resets to 45 instead of 0.

This PR fixes that.

### CODE REVIEW

**Comment by danharrin** [comment]
Hey! Thanks for these fixes. I've made a couple of adjustments - namely adding `min` and `max` attributes to the inputs, so that it's impossible to go to `-1` or `61`, for example. When a value out of range is typed manually, it is now corrected as in your original PR. Suitable adjustments are also made to the preceding unit also - exceeding seconds in a minute will increment the minute as well as setting the seconds to 0.

**Comment by tanthammar** [comment]
Hi @danharrin 
I didn't add the min/max, thought you deliberately skipped it to avoid stopping at 0 on arrow down key :)

**Comment by tanthammar** [comment]
Is it up for discussion, to auto switch day when changing the time?
It's a cool feature, but when thinking about how I would use the picker; I would first click on a day, then use the arrow keys to adjust time. 
Probably hitting the key to fast, so I'd first fast forward, then having to rewind, without noticing that the day I picked has changed. 

Maybe it's just me...

Thoughts?

**Comment by tanthammar** [comment]
@danharrin 

Your changes returned the bug I intended to fix.
The problem is that the code resets the field to current time.
The value must be altered before this line
Example hour.
```
this.hour = Number.isInteger(+this.hour) && this.hour >= 0 && this.hour < 24 ? +this.hour : dayjs().hour()
```

**Comment by tanthammar** [comment]
If you want the feature to go to next/previous day and fix the bug,
Here is a suggestion:

For the hour code:
```js
                this.$watch('hour', () => {
                    if (Number.isInteger(+this.hour)) {
                        if (this.hour > 23) this.hour = 0 & this.focusNextDay()
                        if (this.hour < 0) this.hour = 23 & this.focusPreviousDay()
                        if (this.hour >= 0 && this.hour < 24) this.hour = +this.hour
                    } else {
                        this.hour = dayjs().hour()
                    }

                    let date = this.getSelectedDate()

                    if (date === null) return

                    this.setValue(date.set('hour', this.hour))

                })
```

**Comment by tanthammar** [comment]
Here is my full suggestion to avoid repetition:

Add this method
```js
incrementTime: function (field, switchValue, max) {
                if (Number.isInteger(+field)) {
                    if (field > switchValue) field = 0 & this.focusNextDay()
                    if (field < 0) field = switchValue & this.focusPreviousDay()
                    if (field >= 0 && field < max) field = +field
                } else {
                    field = dayjs().hour()
                }
                return field
            },
```

Then change the watchers
```js
this.$watch('hour', () => {
                    this.hour = this.incrementTime(this.hour, 23, 24)

                    let date = this.getSelectedDate()

                    if (date === null) return

                    this.setValue(date.set('hour', this.hour))

                })

                this.$watch('minute', () => {
                    this.minute = this.incrementTime(this.minute, 59, 60)

                    let date = this.getSelectedDate()

                    if (date === null) return

                    this.setValue(date.set('minute', this.minute))
                })

                this.$watch('second', () => {
                    this.second = this.incrementTime(this.second, 59, 60)

                    let date = this.getSelectedDate()

                    if (date === null) return

                    this.setValue(date.set('second', this.second))
                })
```

**Comment by danharrin** [comment]
Hi @tanthammar, could you please confirm that #347 also fixes the issue? Many thanks.

**Pull request merged**
