### PR TITLE
Add default filter

### PR DESCRIPTION
**Pull request by underdpt**
Hello,

This PR adds the ability to set a default filter on tables. That filter is applied by default if no other filter is selected by the user, and the filter name is shown on the filter dropdown.

From https://github.com/laravel-filament/filament/discussions/551#discussioncomment-1688544

### CODE REVIEW

**Comment by danharrin** [comment]
Hey! Similar to how we have a `defaultSort()` method on the table object, maybe we should have a `defaultFilter()`? Then, we can set the filter property in LW straight from that value and don't need to loop through all filters to find the default one. Thoughts?

**Comment by underdpt** [comment]
Yeah, this way feels cleaner.

**Comment by danharrin** [comment]
Thanks!

**Comment by underdpt** [comment]
My pleasure!

Thanks for your edits, I've learnt something new!

**Comment by danharrin** [comment]
Sorry for the delay merging - been buried in work for v2!

**Pull request merged**
