### PR TITLE
add sort indicator for all sortable columns

### PR DESCRIPTION
**Pull request by maherelgamil**
how can users know the sortable columns? 
So I added a sort indicator to all sortable columns and when the user uses these, it will be shown with different text colors depending on the sorting direction.

image

### CODE REVIEW

**Comment by maherelgamil** [comment]
@ryangjchandler So, how can users know if this column is sortable or not?

**Comment by maherelgamil** [comment]
we can increase the size little

**Comment by danielbidala** [comment]
I agree with @ryangjchandler I would suggest something like this

column-sorting

**Comment by danharrin** [comment]
I agree. Add an `opacity-50` down arrow to sortable columns.

**Comment by maherelgamil** [comment]
Thanks all for reviewing, 

I added `opacity-50` for the down arrow to sortable columns

image

**Comment by danharrin** [comment]
Thanks :)

**Pull request merged**
