### PR TITLE
feat(disabled date): Allow to disable specific date along with minDate & maxDate

### PR DESCRIPTION
**Pull request by saifulapm**
Sometime need to disable specific dates like Booking/Schedule app. I think it will be good one. 

Anyway, Thanks all your hark working and making it awesome.

### CODE REVIEW

**Comment by saifulapm** [comment]
Sorry. I think disabledDates method should accept callback.

**Comment by saifulapm** [comment]
Sorry. I don't know how to push in this pull request. That's I am creating another pull request. Thanks

**Comment by zepfietje** [comment]
@saifulapm just pushing to the PR branch should work.

**Comment by saifulapm** [comment]
oh. Got it.Thank you so much.

**Pull request closed without merging**
