### PR TITLE
Refactor file upload

### PR DESCRIPTION
**Pull request by shuvroroy**

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@shuvroroy What is the aim for this pull request, the description is empty? Are you intending on using the `BaseFileUpload` in any way.

**Comment by danharrin** [comment]
> @shuvroroy What is the aim for this pull request, the description is empty? Are you intending on using the `BaseFileUpload` in any way.

Yeah, I suggested that we extract all the non-Filepond stuff into a base class so that people can create their own upload components.

**Comment by ryangjchandler** [comment]
Yeah, makes sense in that case. Could probably use this for my own Uppy field.

**Comment by danharrin** [comment]
Cheers 🍻

**Pull request merged**
