### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by maherelgamil**

### CODE REVIEW

**Comment by ryangjchandler** [comment]
@maherelgamil You don't actually need the quotes around the version constraint.

**Comment by maherelgamil** [comment]
@ryangjchandler without qouts, we have issue when copy this line directly to terminal

**Comment by danharrin** [comment]
I can't replicate this, and all guides online use the example without quotes. I'm going to close this - let me know if there is another reason why we should consider merging this.

**Comment by ryangjchandler** [comment]
Yeah, I use zsh and can't replicate either.

**Comment by maherelgamil** [comment]
@danharrin @ryangjchandler okay, no problem

**Pull request closed without merging**
