### PR TITLE
Feat: Validation Rule Methods

### PR DESCRIPTION
**Pull request by Z3d0X**
Adds validation rule methods.
Let me know which other rules that should be added.

### CODE REVIEW

**Comment by zepfietje** [comment]
I'm not sure if we should have a method for every single available validation rule, since you can just pass it to the `rule()` or `rules()` method already.

What do you think, @danharrin?

**Comment by danharrin** [comment]
I think we should cover every single Laravel rule 🤷‍♂️ It doesnt add overhead and makes the syntax consistent

**Comment by zepfietje** [comment]
Okay, let's go all the way then.

**Comment by Z3d0X** [comment]
What rules like `exclude` (we already have that functionality from `->dehydrate(false)`)?

**Comment by Z3d0X** [comment]
Sorry I actually completely forgot about this, let me try to get this PR ready for review

**Comment by danharrin** [comment]
A list of rules we dont need:

- Any rule variants that use "if" or "unless" - you can do this with closures
- Bail
- Distinct
- Exclude
- Prohibited
- Required *
- String

**Comment by zepfietje** [comment]
Why don't we need the `string` rule, @danharrin? I wondered this recently as I usually add that rule to my validation but couldn't find any reference in Filament.

**Comment by danharrin** [comment]
I don't see why anyone would really need it?

**Comment by zepfietje** [comment]
Couldn't potentially an array be passed as the value for an input that expects a string? Maybe that's guarded by a type hint, but I'm just evaluating the extremes here.

**Comment by danharrin** [comment]
Apart from those, all done?

**Comment by danharrin** [comment]
Thanks so much for your work on this!

**Pull request merged**
