### PR TITLE
Added Brazilian Portuguese (pt-br) language files

### PR DESCRIPTION
**Pull request by cpereiraweb**
This pull request adds Brazilian Portuguese (pt-br) language files.

### CODE REVIEW

**Comment by danharrin** [comment]
Hey! We went under a heavy localisation refactor a few days and I think some of these are still old translation keys - may you update to the latest version and recheck each please?

Here are the directories that contain translations:
https://github.com/laravel-filament/filament/tree/main/resources/lang
https://github.com/laravel-filament/filament/tree/main/packages/forms/resources/lang
https://github.com/laravel-filament/filament/tree/main/packages/tables/resources/lang

**Comment by EQuimper** [comment]
@danharrin I know it's not about this pr but are you open to have the French translations ? I can do this if you want this :)

**Comment by danharrin** [comment]
> @danharrin I know it's not about this pr but are you open to have the French translations ? I can do this if you want this :)

Hey! Yes, that would be perfect if you could.

**Comment by cpereiraweb** [comment]
Dan, please see if it’s suitable now. I have reviewed all the code.

**Comment by danharrin** [comment]
Thank you so much @cpereiraweb! These are amazing.

**Pull request merged**
