### PR TITLE
Feature: `TagsInput` Handle paste

### PR DESCRIPTION
**Pull request by Z3d0X**
Just splits the tags by `,` on Paste

### CODE REVIEW

**Comment by Z3d0X** [comment]
Oh that is an issue I didn't consider. However, I think we can handle it by checking an _existence_ of a comma in the pasted text, right?

If that ^ doesn't resolve any UX difficulties that arise from this, we can go ahead and close this.

**Comment by zepfietje** [comment]
Still you might want to paste a string containing commas and alter part of it before adding it as tags. I do certainly see the use of this PR, but I'm just not sure if it's worth the trade-off.

**Comment by zepfietje** [comment]
Something like `->createOnPaste()` might be an option if we really want to add it.

**Comment by danharrin** [comment]
I think that they should be created when you paste, if a comma is present within the string.

**Pull request merged**
