### PR TITLE
Brazilian portuguese translations

### PR DESCRIPTION
**Pull request by felipe-balloni**
Initial translations to Brazilian Portuguese, please would review and other users could check and discuss. Thank you.

### CODE REVIEW

**Comment by danharrin** [comment]
Here are the translations from v1 if you wanted to compare - https://github.com/laravel-filament/filament/tree/1.x/resources/lang/pt-br.

**Comment by danharrin** [comment]
If not, I'll merge this PR in a couple of days if everything is okay.

**Comment by felipe-balloni** [comment]
I checked and found some are better than this PR. I'll prefer make some corrections.

**Comment by felipe-balloni** [comment]
Done. Thank you.

**Comment by danharrin** [comment]
Thanks!

**Pull request merged**
