### PR TITLE
Fix little error in TextColumn description position

### PR DESCRIPTION
**Pull request by ralphjsmit**
There was a little accidental error in Dan's changes.

### CODE REVIEW

**Review by zepfietje — APPROVED** [review]

**Review by pxlrbt — APPROVED** [review]

**Comment by ralphjsmit** [comment]
Happy to see that the new team members are actively approving minor fixes 😂

**Comment by ralphjsmit** [comment]
Haha just kidding 🎩

**Comment by pxlrbt** [comment]
> Happy to see that the new team members are actively approving minor fixes 😂

✅ Comment approved.

Looking for the low-hanging fruits to show some activity 😅

**Comment by zepfietje** [comment]
> > Happy to see that the new team members are actively approving minor fixes 😂
> 
> ✅ Comment approved.
> 
> Looking for the low-hanging fruits to show some activity 😜



> > Happy to see that the new team members are actively approving minor fixes 😂
> 
> ✅ Comment approved.
> 
> Looking for the low-hanging fruits to show some activity 😜

Here's another 24 low-hanging fruits: https://github.com/filamentphp/filament/issues.

**Comment by ralphjsmit** [comment]
> Here's another 24 low-hanging fruits: https://github.com/filamentphp/filament/issues.


> _currently unemployed to focus on building open-source tools you love_ 

😜

**Comment by zepfietje** [comment]
> > Here's another 24 low-hanging fruits: https://github.com/filamentphp/filament/issues.
> 
> _**currently unemployed to focus on building open-source tools you love**_
> 
> 😜

## Before

Screen Shot 2022-08-01 at 18 11 22

## After

Screen Shot 2022-08-01 at 18 12 55

**Comment by ralphjsmit** [comment]
> > > Here's another 24 low-hanging fruits: https://github.com/filamentphp/filament/issues.
> > 
> > 
> > _**currently unemployed to focus on building open-source tools you love**_
> > 😜
> 
> ## Before
> Screen Shot 2022-08-01 at 18 11 22
> 
> ## After
> Screen Shot 2022-08-01 at 18 12 55

Lol 😂 You should ask Dan to share 1% of the plugin marketplace revenue with you

**Pull request merged**
