### PR TITLE
Feature: Navigation group objects

### PR DESCRIPTION
**Pull request by oddvalue**
This PR adds a NavigationGroup class to allow navigation groups to be collapsed by default and to add icons to them.

The previous functionality of just specifying the group name is maintained.

## Usage

Registering groups:

```php
use Filament\Facades\Filament;
use Illuminate\Support\ServiceProvider;
use Filament\Navigation\NavigationGroup;

class AppServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        Filament::serving(function () {
            Filament::registerNavigationGroups([
                NavigationGroup::make('Shop')
                    ->icon('heroicon-o-shopping-cart')
                    ->collapsed(),
                NavigationGroup::make('Blog')
                    ->icon('heroicon-o-pencil')
                    ->collapsed(),
                NavigationGroup::make('Settings')
                    ->icon('heroicon-o-cog')
                    ->collapsed(),
            ]);
        });
    }
}
```

Using groups in manual nav:

```php
use Filament\Facades\Filament;
use Filament\Navigation\NavigationBuilder;

Filament::navigation(function (NavigationBuilder $builder): NavigationBuilder {
    return $builder->group(NavigationGroup::make()
        ->label('Content')
        ->items([
            ...PageResource::getNavigationItems(),
            ...CategoryResource::getNavigationItems(),
        ]);
});
```

### CODE REVIEW

**Comment by oddvalue** [comment]
@danharrin I've not made any changes to the auth code so I'm not sure why that test is failing. LoginTest 'it can authenticate' is asserting that the post login redirect should be http://localhost/admin but is actually getting http://localhost, any idea why? Is it actually possible it's something I've done?

**Comment by oddvalue** [comment]
Ignore previous comment. Worked out that the URL is inferred from the nav. Tests should all pass now.

**Comment by oddvalue** [comment]
@danharrin is this likely to be merged at any point? The features are required for a project I'm working on and I'd rather not have to override the core views if possible. 
Thanks!

**Comment by danharrin** [comment]
I've been putting off doing this review because there's alot to get through, sorry 😅 

I feel like I could maybe do the same features with fewer changes, so keeping this open until I make a new PR with the same features

For now, you could always use your fork of Filament in composer.json? But I will try and do the PR very soon

**Comment by oddvalue** [comment]
Awesome, thanks. Just wanted to know it was on the radar :smile:

**Comment by danharrin** [comment]
Replaced by #3216 👍

**Comment by danharrin** [comment]
I removed the `sort()` method from the group as this is defined by the order you register the groups anyway

**Pull request closed without merging**
