### PR TITLE
addRecordActions method in Table 

### PR DESCRIPTION
**Pull request by jszobody**
Per discussion #273 here is a new `addRecordActions` method. 

This will first pull the "Edit" link from the actions array and push it back to the end, ensuring it is always the last action displayed in the table. 

I also added a few tailwind classes to display multiple action icons a bit better.

I can now do this...

```php
->addRecordActions([
    Icon::make('')->icon('heroicon-s-cloud-download'),
    Icon::make('')->icon('heroicon-s-star'),
    Impersonate::make(),
]);
```

... and see this:

CleanShot 2021-03-27 at 09 48 52@2x

### CODE REVIEW

**Comment by jszobody** [comment]
Aight I went ahead with that last option, manually pushing the Edit link to the end of the actions array each time. Seems best to otherwise preserve the order of any added actions.

**Comment by danharrin** [comment]
Hi, I've made this less dependent on `edit` by refactoring it to `pushRecordActions` and `prependRecordActions`. Let me know what you think and I'll merge it :)

**Comment by jszobody** [comment]
Hey! Cool, thanks. Sorry I hadn't gotten back to this sooner.

And of course, this is your project, you don't need my review to merge. ;-)

Here is my only thought, and it's pure coding preference. I love Collections, I use them everywhere, but sometimes creating a collection only to convert right back to an array feels like overkill, especially when it creates more code.

Compare:

```php
$this->recordActions = collect($this->recordActions)
    ->push(
        collect(value($actions))->map(fn ($action) => $action->table($this))
    )
    ->toArray();
```

With:

```php
$this->recordActions = array_merge(
    $this->recordActions, 
    array_map(fn ($action) => $action->table($this), $actions)
);
```

I think I'd slightly lean towards the latter of those two, maybe? 

Whatever you think best. Merge when ready!

**Comment by danharrin** [comment]
Well spotted, I've switched the merge out, but I'm keeping the map as a collection for consistency with other areas of the codebase. Thanks for your work on this and your patience :) Let me know when your plugin launches and I'll promote it!

**Pull request merged**
