### PR TITLE
feature: Validation notifications

### PR DESCRIPTION
**Pull request by danharrin**
Unknown-2

### CODE REVIEW

**Comment by ryangjchandler** [comment]
Can we make this an opt-in?

**Comment by danharrin** [comment]
Yeah that is the plan, why I haven't merged it yet

**Comment by intrepidws** [comment]
This is great! My only thought is whether it might make more sense to have a more general/generic error message, simply alerting the user that errors exist. Especially in cases where multiple fields have validation errors, this might make more sense?

**Comment by intrepidws** [comment]
Would this message occur on form submit? Or automatically as fields change?

**Comment by danharrin** [comment]
On submit, when the fields are validated

**Comment by danharrin** [comment]
```php
use Filament\Pages\Page;

Page::$reportValidationErrorUsing = function (ValidationException $exception) {
    Filament::notify('danger', $exception->getMessage());
};
```

**Comment by tanthammar** [comment]
If I understand this correctly, I would have to add something to every Resource, Create/Update Page if I want to show the errors as notifications?
Or could we combine it with a new config, like "show-form-errors-as-notifications"?

**Comment by intrepidws** [comment]
@tanthammar I was able to add the code that @danharrin provided above to a service provider, instead of adding it to every resource.

That said, I do think this would make sense as a config option. To me, this is expected functionality just like the success notification is.

**Comment by danharrin** [comment]
Trying to move away from more config options as code-driven config is much more flexible IMO, and we just end up polluting the config with so many options

**Comment by tanthammar** [comment]
> @tanthammar I was able to add the code that @danharrin provided above to a service provider, instead of adding it to every resource.
> 
> That said, I do think this would make sense as a config option. To me, this is expected functionality just like the success notification is.

@intrepidws Can you please tell me how you added it to the service provider?

**Comment by intrepidws** [comment]
@tanthammar No problem, the code that I'm using is below but it came more or less directly from what Dan provided here: https://github.com/filamentphp/filament/pull/2906#issuecomment-1181960399:

```php
\Filament\Pages\Page::$reportValidationErrorUsing = function (ValidationException $exception) {
    Filament::notify('danger', $exception->getMessage());
};
```

**Comment by tanthammar** [comment]
@intrepidws just like that, not wrapped in anything? In `register()` or `boot()`? Which service provider?

**Comment by intrepidws** [comment]
@tanthammar In the `boot()` method of the AppServiceProvider would work fine.

**Comment by tanthammar** [comment]
@intrepidws ok tnx. Nothing happens for me. No messages in Admin panel when validating a resource form.

**Pull request merged**
