### PR TITLE
Create CreatedDateRangeFilter.php

### PR DESCRIPTION
**Pull request by ziming**
Feel free to make it into a more generic DateRangeFilter that is not just for created_at

### CODE REVIEW

**Comment by danharrin** [comment]
https://github.com/filamentphp/filament/pull/3406#discussion_r939550277

**Comment by danharrin** [comment]
https://github.com/filamentphp/filament/pull/3406#discussion_r939626881

**Comment by ziming** [comment]
Hi @danharrin 

i have made the DateRangeFilter class more generic now. Would this still be better outside core?

```php
class DateRangeFilter extends Filter
{
    public static function make(?string $name = 'created_at'): static
    {
        return parent::make($name)
            ->form([
                DatePicker::make($name . '_from'),
                DatePicker::make($name . '_until'),
            ])
            ->query(function (Builder $query, array $data) use ($name): Builder {
                return $query
                    ->when(
                        $data[$name . '_from'],
                        fn (Builder $query, $date): Builder => $query->whereDate($name, '>=', $date),
                    )
                    ->when(
                        $data[$name . '_until'],
                        fn (Builder $query, $date): Builder => $query->whereDate($name, '<=', $date),
                    );
            });
    }
}
```

**Comment by danharrin** [comment]
It would still need to handle relationships etc, same as the SelectFilter

**Pull request closed without merging**
