### PR TITLE
Add MorphToMany filter in selects

### PR DESCRIPTION
**Pull request by a21ns1g4ts**
Motivation:
Some models like spatie tags needs complex handler to perform queries. Instead of do a full integration for the MorphToMany relation. We can perform a simple query from a pluck. Like this bellow. What do you think about this ?

```php
MultiSelectFilter::make('tags')
    ->relationship('tags')
    ->options(Tag::getWithType('contact.tags')->pluck('name', 'id'))
```
Peek 2022-03-05 03-06

### CODE REVIEW

**Comment by danharrin** [comment]
Nice, could we also have this for the `SelectFilter`?

**Comment by a21ns1g4ts** [comment]
Yep. think this is possible.

**Comment by a21ns1g4ts** [comment]
@danharrin We can extend this to dynamic values. We can do it?.

**Comment by danharrin** [comment]
Not sure what you mean by that?

**Comment by a21ns1g4ts** [comment]
Implement the MorphToMany relation in getRelationshipOptions method too.
https://github.com/laravel-filament/filament/blob/f4b7fdf91eac39d94325ebf6ed6e6f29fc1785b8/packages/tables/src/Filters/MultiSelectFilter.php#L87
https://github.com/laravel-filament/filament/blob/f4b7fdf91eac39d94325ebf6ed6e6f29fc1785b8/packages/tables/src/Filters/MultiSelectFilter.php#L87

**Comment by a21ns1g4ts** [comment]
now it works like magic 😲

```php 
MultiSelectFilter::make('tags')
    ->relationship('tags', 'name')
```

**Comment by a21ns1g4ts** [comment]
I really like it. The laravel and filament power is wonderful,
```php
SelectFilter::make('tags1')
  ->relationship('tags', 'name'),
SelectFilter::make('tags2')
  ->relationship('tags')
  ->options(Tag::getWithType('contacts.tags')->pluck('name', 'id')),
MultiSelectFilter::make('tags4')
    ->relationship('tags', 'name'),
MultiSelectFilter::make('tags5')
  ->relationship('tags', 'name')
  ->options(Tag::getWithType('contacts.tags')->pluck('name', 'id'))
```
Peek 2022-03-05 14-12

**Comment by danharrin** [comment]
Thank you so much!

> The laravel and filament power is wonderful,

I agree 😎

**Pull request merged**
